# Пример настроек газа в app.toml

# Минимальная цена газа (по умолчанию "0uosmo", для nuahchain используйте "0unuah")
minimum-gas-prices = "0.0025unuah"

# Максимальный газ на одну транзакцию (по умолчанию 60,000,000)
max-gas-wanted-per-tx = "60000000"

# Минимальная цена газа для арбитражных транзакций (в unuah за единицу газа)
# Значение ".1" означает, что транзакция с 1 млн газа будет стоить 0.1 нуаха
arbitrage-min-gas-fee = ".1"

# Минимальная цена газа для транзакций с высоким потреблением
# Значение ".0025" означает, что транзакция с 1 млн газа будет стоить 0.0025 нуаха
min-gas-price-for-high-gas-tx = ".0025"