package types

import (
	"context"
)

// QueryServer defines the gRPC querier service.
type QueryServer interface {
	IsFreeAccount(context.Context, *QueryIsFreeAccountRequest) (*QueryIsFreeAccountResponse, error)
}

// QueryClient defines the gRPC querier client.
type QueryClient interface {
	IsFreeAccount(ctx context.Context, req *QueryIsFreeAccountRequest) (*QueryIsFreeAccountResponse, error)
}

// QueryIsFreeAccountRequest is the request type for the Query/IsFreeAccount RPC method.
type QueryIsFreeAccountRequest struct {
	Address string `json:"address,omitempty"`
}

// QueryIsFreeAccountResponse is the response type for the Query/IsFreeAccount RPC method.
type QueryIsFreeAccountResponse struct {
	IsFree bool `json:"is_free,omitempty"`
}

// ProtoMessage implements proto.Message interface
func (r *QueryIsFreeAccountResponse) ProtoMessage() {}

// Reset implements proto.Message interface
func (r *QueryIsFreeAccountResponse) Reset() {
	*r = QueryIsFreeAccountResponse{}
}

// String implements proto.Message interface
func (r *QueryIsFreeAccountResponse) String() string {
	if r.IsFree {
		return "QueryIsFreeAccountResponse{IsFree: true}"
	}
	return "QueryIsFreeAccountResponse{IsFree: false}"
}

// NewQueryClient creates a new QueryClient instance
func NewQueryClient(cc interface{}) QueryClient {
	// This would normally be generated by protobuf
	return &queryClient{}
}

type queryClient struct{}

func (q *queryClient) IsFreeAccount(ctx context.Context, req *QueryIsFreeAccountRequest) (*QueryIsFreeAccountResponse, error) {
	// This would normally be implemented by gRPC
	return &QueryIsFreeAccountResponse{}, nil
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct{}

func (*UnimplementedQueryServer) IsFreeAccount(context.Context, *QueryIsFreeAccountRequest) (*QueryIsFreeAccountResponse, error) {
	panic("not implemented")
}

// RegisterQueryServer registers the query server
func RegisterQueryServer(s interface{}, srv QueryServer) {
	// This would normally be generated by protobuf
}