// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/usdoracle/v1beta1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the USD oracle module.
type Params struct {
	// Boolean whether the USD oracle module is enabled.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty" yaml:"enabled"`
	// The admin account of the USD oracle module.
	Admin string `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty" yaml:"admin"`
	// Update interval for USD price in seconds (default: 60 seconds)
	UpdateInterval uint64 `protobuf:"varint,3,opt,name=update_interval,json=updateInterval,proto3" json:"update_interval,omitempty" yaml:"update_interval"`
	// Price deviation threshold for alerts (default: 0.05 = 5%)
	PriceDeviationThreshold cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=price_deviation_threshold,json=priceDeviationThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price_deviation_threshold" yaml:"price_deviation_threshold"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_41f28db7e539d24f, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Params) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *Params) GetUpdateInterval() uint64 {
	if m != nil {
		return m.UpdateInterval
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "osmosis.usdoracle.v1beta1.Params")
}

func init() {
	proto.RegisterFile("osmosis/usdoracle/v1beta1/params.proto", fileDescriptor_41f28db7e539d24f)
}

var fileDescriptor_41f28db7e539d24f = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4a, 0xf3, 0x40,
	0x14, 0xc7, 0x33, 0xfd, 0xfa, 0x55, 0x0d, 0x52, 0x25, 0x88, 0xa6, 0x15, 0x92, 0x90, 0x45, 0xe9,
	0x42, 0x33, 0x96, 0xe2, 0xc6, 0x65, 0x2c, 0x88, 0x20, 0x28, 0xc1, 0x95, 0x9b, 0x30, 0x49, 0x86,
	0x64, 0x30, 0xc9, 0x84, 0xcc, 0x34, 0xd8, 0xb5, 0x17, 0xf0, 0x1a, 0xde, 0xa4, 0xcb, 0x2e, 0xc5,
	0x45, 0x90, 0xf6, 0x06, 0x39, 0x81, 0x98, 0x49, 0x44, 0x04, 0x77, 0xf3, 0xde, 0xef, 0xf7, 0xde,
	0xcc, 0xf0, 0x97, 0x47, 0x94, 0x25, 0x94, 0x11, 0x06, 0xe7, 0x2c, 0xa0, 0x39, 0xf2, 0x63, 0x0c,
	0x8b, 0x89, 0x87, 0x39, 0x9a, 0xc0, 0x0c, 0xe5, 0x28, 0x61, 0x56, 0x96, 0x53, 0x4e, 0x95, 0x41,
	0xe3, 0x59, 0xdf, 0x9e, 0xd5, 0x78, 0xc3, 0x83, 0x90, 0x86, 0xb4, 0xb6, 0xe0, 0xd7, 0x49, 0x0c,
	0x0c, 0x07, 0x7e, 0x3d, 0xe1, 0x0a, 0x20, 0x0a, 0x81, 0xcc, 0xd7, 0x8e, 0xdc, 0xbb, 0xab, 0x97,
	0x2b, 0x27, 0xf2, 0x16, 0x4e, 0x91, 0x17, 0xe3, 0x40, 0x05, 0x06, 0x18, 0x6f, 0xdb, 0x4a, 0x55,
	0xea, 0xfd, 0x05, 0x4a, 0xe2, 0x0b, 0xb3, 0x01, 0xa6, 0xd3, 0x2a, 0xca, 0x48, 0xfe, 0x8f, 0x82,
	0x84, 0xa4, 0x6a, 0xc7, 0x00, 0xe3, 0x1d, 0x7b, 0xbf, 0x2a, 0xf5, 0x5d, 0xe1, 0xd6, 0x6d, 0xd3,
	0x11, 0x58, 0xb9, 0x94, 0xf7, 0xe6, 0x59, 0x80, 0x38, 0x76, 0x49, 0xca, 0x71, 0x5e, 0xa0, 0x58,
	0xfd, 0x67, 0x80, 0x71, 0xd7, 0x1e, 0x56, 0xa5, 0x7e, 0x28, 0x26, 0x7e, 0x09, 0xa6, 0xd3, 0x17,
	0x9d, 0xeb, 0xa6, 0xa1, 0x3c, 0x03, 0x79, 0x90, 0xe5, 0xc4, 0xc7, 0x6e, 0x80, 0x0b, 0x82, 0x38,
	0xa1, 0xa9, 0xcb, 0xa3, 0x1c, 0xb3, 0x88, 0xc6, 0x81, 0xda, 0xad, 0x5f, 0x70, 0xb5, 0x2c, 0x75,
	0xe9, 0xbd, 0xd4, 0x8f, 0xc5, 0xff, 0x58, 0xf0, 0x68, 0x11, 0x0a, 0x13, 0xc4, 0x23, 0xeb, 0x06,
	0x87, 0xc8, 0x5f, 0xcc, 0xb0, 0x5f, 0x95, 0xba, 0x21, 0xae, 0xfc, 0x73, 0x9b, 0xe9, 0x1c, 0xd5,
	0x6c, 0xd6, 0xa2, 0xfb, 0x96, 0xd8, 0xb7, 0xcb, 0xb5, 0x06, 0x56, 0x6b, 0x0d, 0x7c, 0xac, 0x35,
	0xf0, 0xb2, 0xd1, 0xa4, 0xd5, 0x46, 0x93, 0xde, 0x36, 0x9a, 0xf4, 0x70, 0x1e, 0x12, 0x1e, 0xcd,
	0x3d, 0xcb, 0xa7, 0x09, 0x6c, 0xc2, 0x39, 0x8d, 0x91, 0xc7, 0xda, 0x02, 0x16, 0xd3, 0x33, 0xf8,
	0xf4, 0x23, 0x57, 0xbe, 0xc8, 0x30, 0xf3, 0x7a, 0x75, 0x06, 0xd3, 0xcf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x32, 0xf7, 0x74, 0x59, 0xf9, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.PriceDeviationThreshold.Size()
		i -= size
		if _, err := m.PriceDeviationThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.UpdateInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UpdateInterval))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintParams(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x12
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.UpdateInterval != 0 {
		n += 1 + sovParams(uint64(m.UpdateInterval))
	}
	l = m.PriceDeviationThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdateInterval", wireType)
			}
			m.UpdateInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdateInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceDeviationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriceDeviationThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
