// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/usertoken/v1beta1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the usertoken module's genesis state.
type GenesisState struct {
	Params     Params       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	UserTokens []*UserToken `protobuf:"bytes,2,rep,name=user_tokens,json=userTokens,proto3" json:"user_tokens,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c3cee4558fd2fd, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetUserTokens() []*UserToken {
	if m != nil {
		return m.UserTokens
	}
	return nil
}

// Params defines the parameters for the module.
type Params struct {
	FounderTranchePrice    cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=founder_tranche_price,json=founderTranchePrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"founder_tranche_price"`
	FounderTrancheAmount   cosmossdk_io_math.Int       `protobuf:"bytes,2,opt,name=founder_tranche_amount,json=founderTrancheAmount,proto3,customtype=cosmossdk.io/math.Int" json:"founder_tranche_amount"`
	BondingCurveStartPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=bonding_curve_start_price,json=bondingCurveStartPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"bonding_curve_start_price"`
	BondingCurveEndPrice   cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=bonding_curve_end_price,json=bondingCurveEndPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"bonding_curve_end_price"`
	BondingCurveMaxSupply  cosmossdk_io_math.Int       `protobuf:"bytes,5,opt,name=bonding_curve_max_supply,json=bondingCurveMaxSupply,proto3,customtype=cosmossdk.io/math.Int" json:"bonding_curve_max_supply"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c3cee4558fd2fd, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// UserToken defines a user-created token.
type UserToken struct {
	Denom                string                `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Creator              string                `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	CurrentSupply        cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=current_supply,json=currentSupply,proto3,customtype=cosmossdk.io/math.Int" json:"current_supply"`
	FounderTokensClaimed cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=founder_tokens_claimed,json=founderTokensClaimed,proto3,customtype=cosmossdk.io/math.Int" json:"founder_tokens_claimed"`
	LbpActive            bool                  `protobuf:"varint,5,opt,name=lbp_active,json=lbpActive,proto3" json:"lbp_active,omitempty"`
	LbpStartTime         int64                 `protobuf:"varint,6,opt,name=lbp_start_time,json=lbpStartTime,proto3" json:"lbp_start_time,omitempty"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_47c3cee4558fd2fd, []int{2}
}
func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return m.Size()
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *UserToken) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *UserToken) GetLbpActive() bool {
	if m != nil {
		return m.LbpActive
	}
	return false
}

func (m *UserToken) GetLbpStartTime() int64 {
	if m != nil {
		return m.LbpStartTime
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "osmosis.usertoken.v1beta1.GenesisState")
	proto.RegisterType((*Params)(nil), "osmosis.usertoken.v1beta1.Params")
	proto.RegisterType((*UserToken)(nil), "osmosis.usertoken.v1beta1.UserToken")
}

func init() {
	proto.RegisterFile("osmosis/usertoken/v1beta1/genesis.proto", fileDescriptor_47c3cee4558fd2fd)
}

var fileDescriptor_47c3cee4558fd2fd = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x1c, 0xc5, 0x9b, 0x95, 0x15, 0xea, 0x8d, 0x49, 0x84, 0x76, 0x64, 0x45, 0x4b, 0x4b, 0x37, 0x89,
	0x6a, 0x12, 0x09, 0xdb, 0xc4, 0x85, 0xdb, 0xba, 0x4e, 0x08, 0x09, 0xc4, 0x94, 0x16, 0x90, 0x76,
	0x20, 0x72, 0x12, 0x93, 0x46, 0x4b, 0xec, 0xc8, 0x76, 0xaa, 0xf6, 0x2b, 0x70, 0xe2, 0x88, 0xb4,
	0x0b, 0x47, 0x8e, 0xfb, 0x18, 0x3b, 0xee, 0x88, 0x38, 0x4c, 0xa8, 0x3d, 0xec, 0xc8, 0x57, 0x40,
	0xb1, 0xdd, 0xa9, 0x05, 0x81, 0x7a, 0xa9, 0x6c, 0xf7, 0xbd, 0x9f, 0x9f, 0xfe, 0x7e, 0x0a, 0x78,
	0x4c, 0x58, 0x42, 0x58, 0xc4, 0xec, 0x8c, 0x21, 0xca, 0xc9, 0x29, 0xc2, 0xf6, 0x60, 0xd7, 0x43,
	0x1c, 0xee, 0xda, 0x21, 0xc2, 0x88, 0x45, 0xcc, 0x4a, 0x29, 0xe1, 0x44, 0xdf, 0x50, 0x42, 0xeb,
	0x46, 0x68, 0x29, 0x61, 0xad, 0x12, 0x92, 0x90, 0x08, 0x95, 0x9d, 0xaf, 0xa4, 0xa1, 0x76, 0x0f,
	0x26, 0x11, 0x26, 0xb6, 0xf8, 0x95, 0x47, 0xcd, 0x33, 0x0d, 0xac, 0xbe, 0x90, 0xd4, 0x2e, 0x87,
	0x1c, 0xe9, 0x1d, 0x50, 0x4a, 0x21, 0x85, 0x09, 0x33, 0xb4, 0x86, 0xd6, 0x5a, 0xd9, 0x7b, 0x64,
	0xfd, 0xf3, 0x16, 0xeb, 0x58, 0x08, 0xdb, 0xe5, 0x8b, 0xab, 0x7a, 0xe1, 0xdb, 0xf5, 0xf9, 0x8e,
	0xe6, 0x28, 0xaf, 0x7e, 0x04, 0x56, 0x72, 0xb9, 0x2b, 0xf4, 0xcc, 0x58, 0x6a, 0x14, 0x5b, 0x2b,
	0x7b, 0xdb, 0xff, 0x41, 0xbd, 0x65, 0x88, 0xf6, 0xf2, 0x13, 0x07, 0x64, 0xd3, 0x25, 0x6b, 0xfe,
	0x2a, 0x82, 0x92, 0xbc, 0x44, 0x7f, 0x0f, 0xaa, 0x1f, 0x49, 0x86, 0x83, 0x1c, 0x4a, 0x21, 0xf6,
	0xfb, 0xc8, 0x4d, 0x69, 0xe4, 0x23, 0x11, 0xb3, 0xdc, 0xde, 0xca, 0x33, 0xfc, 0xb8, 0xaa, 0x3f,
	0xf4, 0xc5, 0x1d, 0x2c, 0x38, 0xb5, 0x22, 0x62, 0x27, 0x90, 0xf7, 0xad, 0x57, 0x28, 0x84, 0xfe,
	0xa8, 0x83, 0x7c, 0xe7, 0xbe, 0x22, 0xf4, 0x24, 0xe0, 0x38, 0xf7, 0xeb, 0x5d, 0xb0, 0xfe, 0x27,
	0x18, 0x26, 0x24, 0xc3, 0xdc, 0x58, 0x12, 0xe4, 0x4d, 0x45, 0xae, 0xfe, 0x4d, 0x7e, 0x89, 0xb9,
	0x53, 0x99, 0x67, 0x1e, 0x08, 0xab, 0xfe, 0x01, 0x6c, 0x78, 0x04, 0x07, 0x11, 0x0e, 0x5d, 0x3f,
	0xa3, 0x03, 0xe4, 0x32, 0x0e, 0x29, 0x57, 0x89, 0x8b, 0x8b, 0x27, 0x5e, 0x57, 0x94, 0xc3, 0x1c,
	0xd2, 0xcd, 0x19, 0x32, 0xf4, 0x09, 0x78, 0x30, 0xcf, 0x47, 0x38, 0x50, 0xf4, 0x5b, 0x8b, 0xd3,
	0x2b, 0xb3, 0xf4, 0x23, 0x1c, 0x48, 0xf6, 0x3b, 0x60, 0xcc, 0xb3, 0x13, 0x38, 0x74, 0x59, 0x96,
	0xa6, 0xf1, 0xc8, 0x58, 0x5e, 0x64, 0x24, 0xd5, 0x59, 0xec, 0x6b, 0x38, 0xec, 0x0a, 0xef, 0xf3,
	0xad, 0x2f, 0x5f, 0xeb, 0x85, 0x4f, 0xd7, 0xe7, 0x3b, 0xb5, 0x69, 0xc1, 0x87, 0x33, 0x15, 0x97,
	0xcf, 0xdc, 0x3c, 0x5b, 0x02, 0xe5, 0x9b, 0x2e, 0xe8, 0x15, 0xb0, 0x1c, 0x20, 0x4c, 0x12, 0xf9,
	0xc8, 0x8e, 0xdc, 0xe8, 0x06, 0xb8, 0xed, 0x53, 0x04, 0x39, 0xa1, 0xf2, 0x89, 0x9c, 0xe9, 0x56,
	0xef, 0x80, 0x35, 0x3f, 0xa3, 0x14, 0x61, 0x3e, 0x0d, 0x5c, 0x5c, 0x24, 0xf0, 0x5d, 0x65, 0x92,
	0x41, 0xe7, 0x1a, 0x21, 0x7a, 0xe8, 0xfa, 0x31, 0x8c, 0x12, 0x14, 0xa8, 0xd9, 0x2e, 0xda, 0x08,
	0xe1, 0x3d, 0x94, 0x56, 0x7d, 0x13, 0x80, 0xd8, 0x4b, 0x5d, 0xe8, 0xf3, 0x68, 0x80, 0xc4, 0x1c,
	0xef, 0x38, 0xe5, 0xd8, 0x4b, 0x0f, 0xc4, 0x81, 0xbe, 0x0d, 0xd6, 0xf2, 0xbf, 0x65, 0x4d, 0x78,
	0x94, 0x20, 0xa3, 0xd4, 0xd0, 0x5a, 0x45, 0x67, 0x35, 0xf6, 0x52, 0xf1, 0xee, 0xbd, 0x28, 0x41,
	0xed, 0x37, 0x17, 0x63, 0x53, 0xbb, 0x1c, 0x9b, 0xda, 0xcf, 0xb1, 0xa9, 0x7d, 0x9e, 0x98, 0x85,
	0xcb, 0x89, 0x59, 0xf8, 0x3e, 0x31, 0x0b, 0x27, 0xcf, 0xc2, 0x88, 0xf7, 0x33, 0xcf, 0xf2, 0x49,
	0x62, 0xab, 0xf1, 0x3e, 0x89, 0xa1, 0xc7, 0xa6, 0x1b, 0x7b, 0xb0, 0xff, 0x74, 0x6e, 0xde, 0x7c,
	0x94, 0x22, 0xe6, 0x95, 0xc4, 0x57, 0x60, 0xff, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x0e,
	0x84, 0x86, 0x74, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserTokens) > 0 {
		for iNdEx := len(m.UserTokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserTokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BondingCurveMaxSupply.Size()
		i -= size
		if _, err := m.BondingCurveMaxSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.BondingCurveEndPrice.Size()
		i -= size
		if _, err := m.BondingCurveEndPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BondingCurveStartPrice.Size()
		i -= size
		if _, err := m.BondingCurveStartPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.FounderTrancheAmount.Size()
		i -= size
		if _, err := m.FounderTrancheAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.FounderTranchePrice.Size()
		i -= size
		if _, err := m.FounderTranchePrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *UserToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LbpStartTime != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LbpStartTime))
		i--
		dAtA[i] = 0x30
	}
	if m.LbpActive {
		i--
		if m.LbpActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.FounderTokensClaimed.Size()
		i -= size
		if _, err := m.FounderTokensClaimed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.CurrentSupply.Size()
		i -= size
		if _, err := m.CurrentSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.UserTokens) > 0 {
		for _, e := range m.UserTokens {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FounderTranchePrice.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.FounderTrancheAmount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.BondingCurveStartPrice.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.BondingCurveEndPrice.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.BondingCurveMaxSupply.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *UserToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.CurrentSupply.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.FounderTokensClaimed.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LbpActive {
		n += 2
	}
	if m.LbpStartTime != 0 {
		n += 1 + sovGenesis(uint64(m.LbpStartTime))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserTokens = append(m.UserTokens, &UserToken{})
			if err := m.UserTokens[len(m.UserTokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FounderTranchePrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FounderTranchePrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FounderTrancheAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FounderTrancheAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingCurveStartPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondingCurveStartPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingCurveEndPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondingCurveEndPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingCurveMaxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BondingCurveMaxSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurrentSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FounderTokensClaimed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FounderTokensClaimed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LbpActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LbpActive = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LbpStartTime", wireType)
			}
			m.LbpStartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LbpStartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
