// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/usertoken/v1beta1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryUserTokenRequest is request type for the Query/UserToken RPC method.
type QueryUserTokenRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryUserTokenRequest) Reset()         { *m = QueryUserTokenRequest{} }
func (m *QueryUserTokenRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserTokenRequest) ProtoMessage()    {}
func (*QueryUserTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{2}
}
func (m *QueryUserTokenRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserTokenRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserTokenRequest.Merge(m, src)
}
func (m *QueryUserTokenRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserTokenRequest proto.InternalMessageInfo

func (m *QueryUserTokenRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QueryUserTokenResponse is response type for the Query/UserToken RPC method.
type QueryUserTokenResponse struct {
	UserToken *UserToken `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
}

func (m *QueryUserTokenResponse) Reset()         { *m = QueryUserTokenResponse{} }
func (m *QueryUserTokenResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserTokenResponse) ProtoMessage()    {}
func (*QueryUserTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{3}
}
func (m *QueryUserTokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserTokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserTokenResponse.Merge(m, src)
}
func (m *QueryUserTokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserTokenResponse proto.InternalMessageInfo

func (m *QueryUserTokenResponse) GetUserToken() *UserToken {
	if m != nil {
		return m.UserToken
	}
	return nil
}

// QueryUserTokensRequest is request type for the Query/UserTokens RPC method.
type QueryUserTokensRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryUserTokensRequest) Reset()         { *m = QueryUserTokensRequest{} }
func (m *QueryUserTokensRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserTokensRequest) ProtoMessage()    {}
func (*QueryUserTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{4}
}
func (m *QueryUserTokensRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserTokensRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserTokensRequest.Merge(m, src)
}
func (m *QueryUserTokensRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserTokensRequest proto.InternalMessageInfo

func (m *QueryUserTokensRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryUserTokensResponse is response type for the Query/UserTokens RPC method.
type QueryUserTokensResponse struct {
	UserTokens []*UserToken        `protobuf:"bytes,1,rep,name=user_tokens,json=userTokens,proto3" json:"user_tokens,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryUserTokensResponse) Reset()         { *m = QueryUserTokensResponse{} }
func (m *QueryUserTokensResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserTokensResponse) ProtoMessage()    {}
func (*QueryUserTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{5}
}
func (m *QueryUserTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserTokensResponse.Merge(m, src)
}
func (m *QueryUserTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserTokensResponse proto.InternalMessageInfo

func (m *QueryUserTokensResponse) GetUserTokens() []*UserToken {
	if m != nil {
		return m.UserTokens
	}
	return nil
}

func (m *QueryUserTokensResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryBondingCurvePriceRequest is request type for the Query/BondingCurvePrice RPC method.
type QueryBondingCurvePriceRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryBondingCurvePriceRequest) Reset()         { *m = QueryBondingCurvePriceRequest{} }
func (m *QueryBondingCurvePriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBondingCurvePriceRequest) ProtoMessage()    {}
func (*QueryBondingCurvePriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{6}
}
func (m *QueryBondingCurvePriceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondingCurvePriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondingCurvePriceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondingCurvePriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondingCurvePriceRequest.Merge(m, src)
}
func (m *QueryBondingCurvePriceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondingCurvePriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondingCurvePriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondingCurvePriceRequest proto.InternalMessageInfo

func (m *QueryBondingCurvePriceRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

// QueryBondingCurvePriceResponse is response type for the Query/BondingCurvePrice RPC method.
type QueryBondingCurvePriceResponse struct {
	Price cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
}

func (m *QueryBondingCurvePriceResponse) Reset()         { *m = QueryBondingCurvePriceResponse{} }
func (m *QueryBondingCurvePriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBondingCurvePriceResponse) ProtoMessage()    {}
func (*QueryBondingCurvePriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_26dd89774309555b, []int{7}
}
func (m *QueryBondingCurvePriceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBondingCurvePriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBondingCurvePriceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBondingCurvePriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBondingCurvePriceResponse.Merge(m, src)
}
func (m *QueryBondingCurvePriceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBondingCurvePriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBondingCurvePriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBondingCurvePriceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "osmosis.usertoken.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "osmosis.usertoken.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryUserTokenRequest)(nil), "osmosis.usertoken.v1beta1.QueryUserTokenRequest")
	proto.RegisterType((*QueryUserTokenResponse)(nil), "osmosis.usertoken.v1beta1.QueryUserTokenResponse")
	proto.RegisterType((*QueryUserTokensRequest)(nil), "osmosis.usertoken.v1beta1.QueryUserTokensRequest")
	proto.RegisterType((*QueryUserTokensResponse)(nil), "osmosis.usertoken.v1beta1.QueryUserTokensResponse")
	proto.RegisterType((*QueryBondingCurvePriceRequest)(nil), "osmosis.usertoken.v1beta1.QueryBondingCurvePriceRequest")
	proto.RegisterType((*QueryBondingCurvePriceResponse)(nil), "osmosis.usertoken.v1beta1.QueryBondingCurvePriceResponse")
}

func init() {
	proto.RegisterFile("osmosis/usertoken/v1beta1/query.proto", fileDescriptor_26dd89774309555b)
}

var fileDescriptor_26dd89774309555b = []byte{
	// 630 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x14, 0x85, 0xe3, 0xa2, 0x44, 0xca, 0x74, 0xd5, 0x21, 0xfc, 0x05, 0x70, 0xa9, 0x0b, 0x6d, 0xa9,
	0x94, 0x99, 0x26, 0x55, 0x50, 0xbb, 0x61, 0x91, 0x16, 0xd8, 0x20, 0x51, 0x22, 0xd8, 0x50, 0xa1,
	0x30, 0x76, 0x46, 0xae, 0xd5, 0xda, 0xe3, 0x7a, 0xec, 0x88, 0x08, 0xb1, 0xe1, 0x09, 0x10, 0x3c,
	0x02, 0x0b, 0x60, 0xc7, 0x8e, 0x57, 0xc8, 0xb2, 0x12, 0x1b, 0xc4, 0xa2, 0x42, 0x09, 0x12, 0xaf,
	0x81, 0x3c, 0x33, 0xb1, 0x9b, 0x44, 0xf9, 0x29, 0x9b, 0xc8, 0x99, 0xdc, 0x73, 0xcf, 0x77, 0xe7,
	0x9e, 0x18, 0xdc, 0x61, 0xdc, 0x65, 0xdc, 0xe1, 0x38, 0xe2, 0x34, 0x08, 0xd9, 0x21, 0xf5, 0x70,
	0xab, 0x6c, 0xd2, 0x90, 0x94, 0xf1, 0x71, 0x44, 0x83, 0x36, 0xf2, 0x03, 0x16, 0x32, 0x78, 0x4d,
	0x95, 0xa1, 0xa4, 0x0c, 0xa9, 0xb2, 0x62, 0xc1, 0x66, 0x36, 0x13, 0x55, 0x38, 0x7e, 0x92, 0x82,
	0xe2, 0x0d, 0x9b, 0x31, 0xfb, 0x88, 0x62, 0xe2, 0x3b, 0x98, 0x78, 0x1e, 0x0b, 0x49, 0xe8, 0x30,
	0x8f, 0xab, 0x5f, 0xd7, 0x2d, 0xd1, 0x0f, 0x9b, 0x84, 0x53, 0xe9, 0x93, 0xb8, 0xfa, 0xc4, 0x76,
	0x3c, 0x51, 0xac, 0x6a, 0x57, 0xc7, 0x13, 0xda, 0xd4, 0xa3, 0x31, 0x94, 0x2c, 0x5c, 0x20, 0xae,
	0xe3, 0x31, 0x2c, 0x3e, 0xe5, 0x91, 0x51, 0x00, 0xf0, 0x69, 0xdc, 0x7d, 0x8f, 0x04, 0xc4, 0xe5,
	0x75, 0x7a, 0x1c, 0x51, 0x1e, 0x1a, 0xfb, 0xe0, 0xe2, 0xc0, 0x29, 0xf7, 0x99, 0xc7, 0x29, 0xdc,
	0x05, 0x39, 0x5f, 0x9c, 0x5c, 0xd5, 0x6e, 0x69, 0x6b, 0xf3, 0x95, 0x25, 0x34, 0x76, 0x68, 0x24,
	0xa5, 0xb5, 0x7c, 0xe7, 0x74, 0x31, 0xf3, 0xe5, 0xef, 0xb7, 0x75, 0xad, 0xae, 0xb4, 0x46, 0x09,
	0x5c, 0x12, 0xcd, 0x9f, 0x73, 0x1a, 0x3c, 0x8b, 0x35, 0xca, 0x15, 0x16, 0x40, 0xb6, 0x49, 0x3d,
	0xe6, 0x8a, 0xee, 0xf9, 0xba, 0xfc, 0x62, 0xbc, 0x04, 0x97, 0x87, 0xcb, 0x15, 0xce, 0x0e, 0x00,
	0xb1, 0x6f, 0x43, 0x18, 0x2b, 0xa4, 0xdb, 0x13, 0x90, 0xd2, 0x0e, 0xf9, 0xa8, 0xff, 0x68, 0xbc,
	0x1a, 0x6e, 0xdf, 0xbf, 0x04, 0xf8, 0x10, 0x80, 0xf4, 0xaa, 0x55, 0xfb, 0x15, 0x24, 0xf7, 0x82,
	0xe2, 0xbd, 0x20, 0xb9, 0xff, 0x74, 0x62, 0x9b, 0x2a, 0x6d, 0xfd, 0x8c, 0xd2, 0xf8, 0xaa, 0x81,
	0x2b, 0x23, 0x16, 0x6a, 0x84, 0x07, 0x60, 0x3e, 0x1d, 0x21, 0xbe, 0xd6, 0x0b, 0x33, 0xcf, 0x00,
	0x92, 0x19, 0x38, 0x7c, 0x34, 0x80, 0x3a, 0x27, 0x50, 0x57, 0xa7, 0xa2, 0x4a, 0x86, 0x01, 0xd6,
	0x2a, 0xb8, 0x29, 0x50, 0x6b, 0xcc, 0x6b, 0x3a, 0x9e, 0xbd, 0x13, 0x05, 0x2d, 0xba, 0x17, 0x38,
	0x16, 0x9d, 0xbc, 0xa3, 0x7d, 0xa0, 0x8f, 0x93, 0xa9, 0x41, 0xb7, 0x41, 0xd6, 0x8f, 0x0f, 0xa4,
	0xae, 0xb6, 0x1c, 0xc7, 0xe2, 0xd7, 0xe9, 0xe2, 0x75, 0xc9, 0xc8, 0x9b, 0x87, 0xc8, 0x61, 0xd8,
	0x25, 0xe1, 0x01, 0x7a, 0x4c, 0x6d, 0x62, 0xb5, 0x77, 0xa9, 0x55, 0x97, 0x8a, 0xca, 0xf7, 0x2c,
	0xc8, 0x8a, 0xee, 0xf0, 0x83, 0x06, 0x72, 0x32, 0x57, 0xb0, 0x34, 0xe1, 0x8e, 0x46, 0x03, 0x5d,
	0x44, 0xb3, 0x96, 0x4b, 0x5c, 0xe3, 0xee, 0xbb, 0x1f, 0x7f, 0x3e, 0xce, 0x2d, 0xc3, 0x25, 0x3c,
	0xfe, 0xbf, 0x25, 0xe3, 0x0c, 0x3f, 0x6b, 0x20, 0x9f, 0x6c, 0x05, 0x6e, 0x4c, 0x33, 0x1a, 0x4e,
	0x7d, 0xb1, 0x7c, 0x0e, 0x85, 0xa2, 0xab, 0x0a, 0x3a, 0x0c, 0x4b, 0x13, 0xe8, 0xd2, 0x58, 0xe1,
	0x37, 0x62, 0x49, 0x6f, 0xe1, 0x27, 0x0d, 0x80, 0x34, 0x83, 0x70, 0x76, 0xe3, 0xe4, 0x1a, 0x2b,
	0xe7, 0x91, 0x28, 0x58, 0x24, 0x60, 0xd7, 0xe0, 0xca, 0x4c, 0xb0, 0x1c, 0x76, 0x34, 0xb0, 0x30,
	0x92, 0x23, 0xb8, 0x35, 0xcd, 0x79, 0x5c, 0x62, 0x8b, 0xdb, 0xff, 0xa1, 0x54, 0xe8, 0xf7, 0x05,
	0xfa, 0x16, 0xbc, 0x37, 0x01, 0xdd, 0x94, 0xea, 0x86, 0x15, 0xcb, 0x1b, 0x22, 0xb1, 0xfd, 0x0b,
	0xaf, 0x3d, 0xe9, 0x74, 0x75, 0xed, 0xa4, 0xab, 0x6b, 0xbf, 0xbb, 0xba, 0xf6, 0xbe, 0xa7, 0x67,
	0x4e, 0x7a, 0x7a, 0xe6, 0x67, 0x4f, 0xcf, 0xbc, 0xa8, 0xda, 0x4e, 0x78, 0x10, 0x99, 0xc8, 0x62,
	0x6e, 0xbf, 0x77, 0xe9, 0x88, 0x98, 0x3c, 0x31, 0x6a, 0x6d, 0x6e, 0xe0, 0xd7, 0x67, 0xec, 0xc2,
	0xb6, 0x4f, 0xb9, 0x99, 0x13, 0x2f, 0xed, 0xcd, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xef,
	0x4a, 0x0a, 0x94, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// UserToken queries a user token by denom.
	UserToken(ctx context.Context, in *QueryUserTokenRequest, opts ...grpc.CallOption) (*QueryUserTokenResponse, error)
	// UserTokens queries all user tokens.
	UserTokens(ctx context.Context, in *QueryUserTokensRequest, opts ...grpc.CallOption) (*QueryUserTokensResponse, error)
	// BondingCurvePrice queries the current bonding curve price for a token.
	BondingCurvePrice(ctx context.Context, in *QueryBondingCurvePriceRequest, opts ...grpc.CallOption) (*QueryBondingCurvePriceResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/osmosis.usertoken.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserToken(ctx context.Context, in *QueryUserTokenRequest, opts ...grpc.CallOption) (*QueryUserTokenResponse, error) {
	out := new(QueryUserTokenResponse)
	err := c.cc.Invoke(ctx, "/osmosis.usertoken.v1beta1.Query/UserToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserTokens(ctx context.Context, in *QueryUserTokensRequest, opts ...grpc.CallOption) (*QueryUserTokensResponse, error) {
	out := new(QueryUserTokensResponse)
	err := c.cc.Invoke(ctx, "/osmosis.usertoken.v1beta1.Query/UserTokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BondingCurvePrice(ctx context.Context, in *QueryBondingCurvePriceRequest, opts ...grpc.CallOption) (*QueryBondingCurvePriceResponse, error) {
	out := new(QueryBondingCurvePriceResponse)
	err := c.cc.Invoke(ctx, "/osmosis.usertoken.v1beta1.Query/BondingCurvePrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// UserToken queries a user token by denom.
	UserToken(context.Context, *QueryUserTokenRequest) (*QueryUserTokenResponse, error)
	// UserTokens queries all user tokens.
	UserTokens(context.Context, *QueryUserTokensRequest) (*QueryUserTokensResponse, error)
	// BondingCurvePrice queries the current bonding curve price for a token.
	BondingCurvePrice(context.Context, *QueryBondingCurvePriceRequest) (*QueryBondingCurvePriceResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) UserToken(ctx context.Context, req *QueryUserTokenRequest) (*QueryUserTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserToken not implemented")
}
func (*UnimplementedQueryServer) UserTokens(ctx context.Context, req *QueryUserTokensRequest) (*QueryUserTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserTokens not implemented")
}
func (*UnimplementedQueryServer) BondingCurvePrice(ctx context.Context, req *QueryBondingCurvePriceRequest) (*QueryBondingCurvePriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BondingCurvePrice not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.usertoken.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.usertoken.v1beta1.Query/UserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserToken(ctx, req.(*QueryUserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.usertoken.v1beta1.Query/UserTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserTokens(ctx, req.(*QueryUserTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BondingCurvePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBondingCurvePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BondingCurvePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.usertoken.v1beta1.Query/BondingCurvePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BondingCurvePrice(ctx, req.(*QueryBondingCurvePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.usertoken.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "UserToken",
			Handler:    _Query_UserToken_Handler,
		},
		{
			MethodName: "UserTokens",
			Handler:    _Query_UserTokens_Handler,
		},
		{
			MethodName: "BondingCurvePrice",
			Handler:    _Query_BondingCurvePrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/usertoken/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryUserTokenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserTokenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserTokenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserTokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserTokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserTokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UserToken != nil {
		{
			size, err := m.UserToken.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserTokensRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserTokensRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserTokensRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserTokens) > 0 {
		for iNdEx := len(m.UserTokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserTokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondingCurvePriceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondingCurvePriceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondingCurvePriceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBondingCurvePriceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBondingCurvePriceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBondingCurvePriceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryUserTokenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserTokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.UserToken != nil {
		l = m.UserToken.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserTokensRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.UserTokens) > 0 {
		for _, e := range m.UserTokens {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBondingCurvePriceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBondingCurvePriceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Price.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserTokenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserTokenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserTokenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserTokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserTokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserTokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserToken", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UserToken == nil {
				m.UserToken = &UserToken{}
			}
			if err := m.UserToken.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserTokensRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserTokensRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserTokensRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserTokens = append(m.UserTokens, &UserToken{})
			if err := m.UserTokens[len(m.UserTokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondingCurvePriceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondingCurvePriceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondingCurvePriceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBondingCurvePriceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBondingCurvePriceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBondingCurvePriceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
