// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/usertoken/v1beta1/token.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Creator      string            `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Denom        string            `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	Name         string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol       string            `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Image        string            `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Description  string            `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt    uint64            `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Distribution TokenDistribution `protobuf:"bytes,8,opt,name=distribution,proto3" json:"distribution"`
	State        TokenState        `protobuf:"bytes,9,opt,name=state,proto3" json:"state"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b139fed12cfde8b, []int{0}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Token.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return m.Size()
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Token) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *Token) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Token) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Token) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Token) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Token) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Token) GetDistribution() TokenDistribution {
	if m != nil {
		return m.Distribution
	}
	return TokenDistribution{}
}

func (m *Token) GetState() TokenState {
	if m != nil {
		return m.State
	}
	return TokenState{}
}

type TokenDistribution struct {
	TotalSupply          string `protobuf:"bytes,1,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	BondingCurveSupply   string `protobuf:"bytes,2,opt,name=bonding_curve_supply,json=bondingCurveSupply,proto3" json:"bonding_curve_supply,omitempty"`
	PlatformWallet       string `protobuf:"bytes,3,opt,name=platform_wallet,json=platformWallet,proto3" json:"platform_wallet,omitempty"`
	ReferralWallet       string `protobuf:"bytes,4,opt,name=referral_wallet,json=referralWallet,proto3" json:"referral_wallet,omitempty"`
	AiCeoWallet          string `protobuf:"bytes,5,opt,name=ai_ceo_wallet,json=aiCeoWallet,proto3" json:"ai_ceo_wallet,omitempty"`
	FounderReserved      string `protobuf:"bytes,6,opt,name=founder_reserved,json=founderReserved,proto3" json:"founder_reserved,omitempty"`
	FounderClaimed       bool   `protobuf:"varint,7,opt,name=founder_claimed,json=founderClaimed,proto3" json:"founder_claimed,omitempty"`
	FounderClaimDeadline uint64 `protobuf:"varint,8,opt,name=founder_claim_deadline,json=founderClaimDeadline,proto3" json:"founder_claim_deadline,omitempty"`
}

func (m *TokenDistribution) Reset()         { *m = TokenDistribution{} }
func (m *TokenDistribution) String() string { return proto.CompactTextString(m) }
func (*TokenDistribution) ProtoMessage()    {}
func (*TokenDistribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b139fed12cfde8b, []int{1}
}
func (m *TokenDistribution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenDistribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenDistribution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenDistribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenDistribution.Merge(m, src)
}
func (m *TokenDistribution) XXX_Size() int {
	return m.Size()
}
func (m *TokenDistribution) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenDistribution.DiscardUnknown(m)
}

var xxx_messageInfo_TokenDistribution proto.InternalMessageInfo

func (m *TokenDistribution) GetTotalSupply() string {
	if m != nil {
		return m.TotalSupply
	}
	return ""
}

func (m *TokenDistribution) GetBondingCurveSupply() string {
	if m != nil {
		return m.BondingCurveSupply
	}
	return ""
}

func (m *TokenDistribution) GetPlatformWallet() string {
	if m != nil {
		return m.PlatformWallet
	}
	return ""
}

func (m *TokenDistribution) GetReferralWallet() string {
	if m != nil {
		return m.ReferralWallet
	}
	return ""
}

func (m *TokenDistribution) GetAiCeoWallet() string {
	if m != nil {
		return m.AiCeoWallet
	}
	return ""
}

func (m *TokenDistribution) GetFounderReserved() string {
	if m != nil {
		return m.FounderReserved
	}
	return ""
}

func (m *TokenDistribution) GetFounderClaimed() bool {
	if m != nil {
		return m.FounderClaimed
	}
	return false
}

func (m *TokenDistribution) GetFounderClaimDeadline() uint64 {
	if m != nil {
		return m.FounderClaimDeadline
	}
	return 0
}

type TokenState struct {
	BondingCurveSold  string `protobuf:"bytes,1,opt,name=bonding_curve_sold,json=bondingCurveSold,proto3" json:"bonding_curve_sold,omitempty"`
	CurrentPrice      string `protobuf:"bytes,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	CurveCompleted    bool   `protobuf:"varint,3,opt,name=curve_completed,json=curveCompleted,proto3" json:"curve_completed,omitempty"`
	DexTradingEnabled bool   `protobuf:"varint,4,opt,name=dex_trading_enabled,json=dexTradingEnabled,proto3" json:"dex_trading_enabled,omitempty"`
	SoftLockEnabled   bool   `protobuf:"varint,5,opt,name=soft_lock_enabled,json=softLockEnabled,proto3" json:"soft_lock_enabled,omitempty"`
}

func (m *TokenState) Reset()         { *m = TokenState{} }
func (m *TokenState) String() string { return proto.CompactTextString(m) }
func (*TokenState) ProtoMessage()    {}
func (*TokenState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b139fed12cfde8b, []int{2}
}
func (m *TokenState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TokenState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TokenState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TokenState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenState.Merge(m, src)
}
func (m *TokenState) XXX_Size() int {
	return m.Size()
}
func (m *TokenState) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenState.DiscardUnknown(m)
}

var xxx_messageInfo_TokenState proto.InternalMessageInfo

func (m *TokenState) GetBondingCurveSold() string {
	if m != nil {
		return m.BondingCurveSold
	}
	return ""
}

func (m *TokenState) GetCurrentPrice() string {
	if m != nil {
		return m.CurrentPrice
	}
	return ""
}

func (m *TokenState) GetCurveCompleted() bool {
	if m != nil {
		return m.CurveCompleted
	}
	return false
}

func (m *TokenState) GetDexTradingEnabled() bool {
	if m != nil {
		return m.DexTradingEnabled
	}
	return false
}

func (m *TokenState) GetSoftLockEnabled() bool {
	if m != nil {
		return m.SoftLockEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Token)(nil), "osmosis.usertoken.v1beta1.Token")
	proto.RegisterType((*TokenDistribution)(nil), "osmosis.usertoken.v1beta1.TokenDistribution")
	proto.RegisterType((*TokenState)(nil), "osmosis.usertoken.v1beta1.TokenState")
}

func init() {
	proto.RegisterFile("osmosis/usertoken/v1beta1/token.proto", fileDescriptor_8b139fed12cfde8b)
}

var fileDescriptor_8b139fed12cfde8b = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0xc7, 0x9b, 0x7d, 0xed, 0xd6, 0xb9, 0x5b, 0xb7, 0xf9, 0xab, 0xa6, 0x80, 0x44, 0x28, 0x45,
	0x13, 0x03, 0x8d, 0x64, 0x63, 0xf0, 0x00, 0x5b, 0xc7, 0x1d, 0x12, 0x28, 0x9b, 0x40, 0xe2, 0x26,
	0x72, 0xe2, 0xd3, 0x62, 0xcd, 0x89, 0x23, 0xdb, 0x29, 0xeb, 0x5b, 0xf0, 0x58, 0xbb, 0xdc, 0x0d,
	0x12, 0x57, 0x08, 0xb5, 0x5c, 0xf0, 0x18, 0x28, 0x8e, 0x33, 0x5a, 0x10, 0xe2, 0x2e, 0xe7, 0x77,
	0x7e, 0x3e, 0x6e, 0xfe, 0xa7, 0x0a, 0xda, 0x13, 0x2a, 0x15, 0x8a, 0xa9, 0xa0, 0x50, 0x20, 0xb5,
	0xb8, 0x84, 0x2c, 0x98, 0x1c, 0xc5, 0xa0, 0xc9, 0x51, 0x60, 0x2a, 0x3f, 0x97, 0x42, 0x0b, 0x7c,
	0xc7, 0x6a, 0xfe, 0xad, 0xe6, 0x5b, 0xed, 0x6e, 0x6f, 0x2c, 0xc6, 0xc2, 0x58, 0x41, 0xf9, 0x54,
	0x1d, 0x18, 0x7c, 0x5e, 0x41, 0xad, 0x8b, 0xd2, 0xc3, 0x2e, 0x5a, 0x4b, 0x24, 0x10, 0x2d, 0xa4,
	0xeb, 0xf4, 0x9d, 0xfd, 0xf5, 0xb0, 0x2e, 0x71, 0x0f, 0xb5, 0x28, 0x64, 0x22, 0x75, 0x57, 0x0c,
	0xaf, 0x0a, 0x8c, 0x51, 0x33, 0x23, 0x29, 0xb8, 0xff, 0x19, 0x68, 0x9e, 0xf1, 0x2e, 0x5a, 0x55,
	0xd3, 0x34, 0x16, 0xdc, 0x6d, 0x1a, 0x6a, 0xab, 0x72, 0x02, 0x4b, 0xc9, 0x18, 0xdc, 0x56, 0x35,
	0xc1, 0x14, 0xb8, 0x8f, 0x3a, 0x14, 0x54, 0x22, 0x59, 0xae, 0x99, 0xc8, 0xdc, 0x55, 0xd3, 0x5b,
	0x44, 0xf8, 0x1e, 0x42, 0xe6, 0x47, 0x00, 0x8d, 0x88, 0x76, 0xd7, 0xfa, 0xce, 0x7e, 0x33, 0x5c,
	0xb7, 0xe4, 0x44, 0xe3, 0xb7, 0x68, 0x83, 0x32, 0xa5, 0x25, 0x8b, 0x0b, 0x33, 0xa1, 0xdd, 0x77,
	0xf6, 0x3b, 0xcf, 0x0e, 0xfc, 0xbf, 0x86, 0xe0, 0x9b, 0x57, 0x3d, 0x5b, 0x38, 0x73, 0xda, 0xbc,
	0xfe, 0x7a, 0xbf, 0x11, 0x2e, 0xcd, 0xc1, 0x27, 0xa8, 0xa5, 0x34, 0xd1, 0xe0, 0xae, 0x9b, 0x81,
	0x7b, 0xff, 0x1a, 0x78, 0x5e, 0xca, 0x76, 0x52, 0x75, 0x72, 0xf0, 0x63, 0x05, 0xed, 0xfc, 0x71,
	0x19, 0x7e, 0x80, 0x36, 0xb4, 0xd0, 0x84, 0x47, 0xaa, 0xc8, 0x73, 0x3e, 0xb5, 0x41, 0x77, 0x0c,
	0x3b, 0x37, 0x08, 0x1f, 0xa2, 0x5e, 0x2c, 0x32, 0xca, 0xb2, 0x71, 0x94, 0x14, 0x72, 0x02, 0xb5,
	0x5a, 0x65, 0x8f, 0x6d, 0x6f, 0x58, 0xb6, 0xec, 0x89, 0x47, 0x68, 0x2b, 0xe7, 0x44, 0x8f, 0x84,
	0x4c, 0xa3, 0x8f, 0x84, 0x73, 0xd0, 0x76, 0x27, 0xdd, 0x1a, 0xbf, 0x33, 0xb4, 0x14, 0x25, 0x8c,
	0x40, 0x4a, 0xc2, 0x6b, 0xb1, 0x5a, 0x53, 0xb7, 0xc6, 0x56, 0x1c, 0xa0, 0x4d, 0xc2, 0xa2, 0x04,
	0x44, 0xad, 0x55, 0x6b, 0xeb, 0x10, 0x36, 0x04, 0x61, 0x9d, 0xc7, 0x68, 0x7b, 0x24, 0x8a, 0x8c,
	0x82, 0x8c, 0x24, 0x28, 0x90, 0x13, 0xa0, 0x76, 0x83, 0x5b, 0x96, 0x87, 0x16, 0x97, 0xf7, 0xd6,
	0x6a, 0xc2, 0x09, 0x4b, 0x81, 0x9a, 0x55, 0xb6, 0xc3, 0xae, 0xc5, 0xc3, 0x8a, 0xe2, 0xe7, 0x68,
	0x77, 0x49, 0x8c, 0x28, 0x10, 0xca, 0x59, 0x06, 0x66, 0xb3, 0xcd, 0xb0, 0xb7, 0xe8, 0x9f, 0xd9,
	0xde, 0xe0, 0xbb, 0x83, 0xd0, 0xaf, 0x35, 0xe0, 0x03, 0x84, 0x7f, 0x0b, 0x50, 0x70, 0x6a, 0x93,
	0xde, 0x5e, 0x8a, 0x4f, 0x70, 0x8a, 0x1f, 0xa2, 0xcd, 0xa4, 0x90, 0x12, 0x32, 0x1d, 0xe5, 0x92,
	0x25, 0x60, 0x73, 0xde, 0xb0, 0xf0, 0x4d, 0xc9, 0xca, 0x17, 0xa8, 0x46, 0x25, 0x22, 0xcd, 0x39,
	0x68, 0xa0, 0x26, 0xe1, 0x76, 0xd8, 0x35, 0x78, 0x58, 0x53, 0xec, 0xa3, 0xff, 0x29, 0x5c, 0x45,
	0x5a, 0x12, 0x73, 0x3f, 0x64, 0x24, 0xe6, 0x40, 0x4d, 0xca, 0xed, 0x70, 0x87, 0xc2, 0xd5, 0x45,
	0xd5, 0x79, 0x59, 0x35, 0xf0, 0x13, 0xb4, 0xa3, 0xc4, 0x48, 0x47, 0x5c, 0x24, 0x97, 0xb7, 0x76,
	0xcb, 0xd8, 0x5b, 0x65, 0xe3, 0x95, 0x48, 0x2e, 0xad, 0x7b, 0xfa, 0xfa, 0x7a, 0xe6, 0x39, 0x37,
	0x33, 0xcf, 0xf9, 0x36, 0xf3, 0x9c, 0x4f, 0x73, 0xaf, 0x71, 0x33, 0xf7, 0x1a, 0x5f, 0xe6, 0x5e,
	0xe3, 0xfd, 0x8b, 0x31, 0xd3, 0x1f, 0x8a, 0xd8, 0x4f, 0x44, 0x1a, 0xd8, 0x7f, 0xea, 0x53, 0x4e,
	0x62, 0x55, 0x17, 0xc1, 0xe4, 0xf8, 0x30, 0xb8, 0x5a, 0xf8, 0x72, 0xe8, 0x69, 0x0e, 0x2a, 0x5e,
	0x35, 0x5f, 0x80, 0xe3, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x1b, 0x71, 0xa2, 0x5b, 0x04,
	0x00, 0x00,
}

func (m *Token) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Token) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Token) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintToken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size, err := m.Distribution.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintToken(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.CreatedAt != 0 {
		i = encodeVarintToken(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintToken(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TokenDistribution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenDistribution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenDistribution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FounderClaimDeadline != 0 {
		i = encodeVarintToken(dAtA, i, uint64(m.FounderClaimDeadline))
		i--
		dAtA[i] = 0x40
	}
	if m.FounderClaimed {
		i--
		if m.FounderClaimed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if len(m.FounderReserved) > 0 {
		i -= len(m.FounderReserved)
		copy(dAtA[i:], m.FounderReserved)
		i = encodeVarintToken(dAtA, i, uint64(len(m.FounderReserved)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.AiCeoWallet) > 0 {
		i -= len(m.AiCeoWallet)
		copy(dAtA[i:], m.AiCeoWallet)
		i = encodeVarintToken(dAtA, i, uint64(len(m.AiCeoWallet)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ReferralWallet) > 0 {
		i -= len(m.ReferralWallet)
		copy(dAtA[i:], m.ReferralWallet)
		i = encodeVarintToken(dAtA, i, uint64(len(m.ReferralWallet)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PlatformWallet) > 0 {
		i -= len(m.PlatformWallet)
		copy(dAtA[i:], m.PlatformWallet)
		i = encodeVarintToken(dAtA, i, uint64(len(m.PlatformWallet)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BondingCurveSupply) > 0 {
		i -= len(m.BondingCurveSupply)
		copy(dAtA[i:], m.BondingCurveSupply)
		i = encodeVarintToken(dAtA, i, uint64(len(m.BondingCurveSupply)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TotalSupply) > 0 {
		i -= len(m.TotalSupply)
		copy(dAtA[i:], m.TotalSupply)
		i = encodeVarintToken(dAtA, i, uint64(len(m.TotalSupply)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TokenState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TokenState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TokenState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SoftLockEnabled {
		i--
		if m.SoftLockEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.DexTradingEnabled {
		i--
		if m.DexTradingEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.CurveCompleted {
		i--
		if m.CurveCompleted {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.CurrentPrice) > 0 {
		i -= len(m.CurrentPrice)
		copy(dAtA[i:], m.CurrentPrice)
		i = encodeVarintToken(dAtA, i, uint64(len(m.CurrentPrice)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BondingCurveSold) > 0 {
		i -= len(m.BondingCurveSold)
		copy(dAtA[i:], m.BondingCurveSold)
		i = encodeVarintToken(dAtA, i, uint64(len(m.BondingCurveSold)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Token) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovToken(uint64(m.CreatedAt))
	}
	l = m.Distribution.Size()
	n += 1 + l + sovToken(uint64(l))
	l = m.State.Size()
	n += 1 + l + sovToken(uint64(l))
	return n
}

func (m *TokenDistribution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TotalSupply)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.BondingCurveSupply)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.PlatformWallet)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.ReferralWallet)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.AiCeoWallet)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.FounderReserved)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	if m.FounderClaimed {
		n += 2
	}
	if m.FounderClaimDeadline != 0 {
		n += 1 + sovToken(uint64(m.FounderClaimDeadline))
	}
	return n
}

func (m *TokenState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BondingCurveSold)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	l = len(m.CurrentPrice)
	if l > 0 {
		n += 1 + l + sovToken(uint64(l))
	}
	if m.CurveCompleted {
		n += 2
	}
	if m.DexTradingEnabled {
		n += 2
	}
	if m.SoftLockEnabled {
		n += 2
	}
	return n
}

func sovToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozToken(x uint64) (n int) {
	return sovToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Token) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Token: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Token: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Distribution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Distribution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenDistribution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenDistribution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenDistribution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingCurveSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondingCurveSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformWallet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlatformWallet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralWallet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReferralWallet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AiCeoWallet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AiCeoWallet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FounderReserved", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FounderReserved = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FounderClaimed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FounderClaimed = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FounderClaimDeadline", wireType)
			}
			m.FounderClaimDeadline = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FounderClaimDeadline |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TokenState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TokenState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TokenState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingCurveSold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondingCurveSold = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurveCompleted", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CurveCompleted = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DexTradingEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DexTradingEnabled = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SoftLockEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SoftLockEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupToken = fmt.Errorf("proto: unexpected end of group")
)
