// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/policy/v1beta1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreatePolicy struct {
	Owner          string            `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	PolicyType     string            `protobuf:"bytes,2,opt,name=policy_type,json=policyType,proto3" json:"policy_type,omitempty"`
	Attributes     []PolicyAttribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes"`
	TreasuryPoolId string            `protobuf:"bytes,4,opt,name=treasury_pool_id,json=treasuryPoolId,proto3" json:"treasury_pool_id,omitempty"`
	StartTime      *time.Time        `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time,omitempty"`
	EndTime        *time.Time        `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time,omitempty"`
	Tags           []string          `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (m *MsgCreatePolicy) Reset()         { *m = MsgCreatePolicy{} }
func (m *MsgCreatePolicy) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePolicy) ProtoMessage()    {}
func (*MsgCreatePolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{0}
}
func (m *MsgCreatePolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePolicy.Merge(m, src)
}
func (m *MsgCreatePolicy) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePolicy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePolicy proto.InternalMessageInfo

func (m *MsgCreatePolicy) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgCreatePolicy) GetPolicyType() string {
	if m != nil {
		return m.PolicyType
	}
	return ""
}

func (m *MsgCreatePolicy) GetAttributes() []PolicyAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *MsgCreatePolicy) GetTreasuryPoolId() string {
	if m != nil {
		return m.TreasuryPoolId
	}
	return ""
}

func (m *MsgCreatePolicy) GetStartTime() *time.Time {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *MsgCreatePolicy) GetEndTime() *time.Time {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *MsgCreatePolicy) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type MsgCreatePolicyResponse struct {
	PolicyId uint64 `protobuf:"varint,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
}

func (m *MsgCreatePolicyResponse) Reset()         { *m = MsgCreatePolicyResponse{} }
func (m *MsgCreatePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePolicyResponse) ProtoMessage()    {}
func (*MsgCreatePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{1}
}
func (m *MsgCreatePolicyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePolicyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePolicyResponse.Merge(m, src)
}
func (m *MsgCreatePolicyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePolicyResponse proto.InternalMessageInfo

func (m *MsgCreatePolicyResponse) GetPolicyId() uint64 {
	if m != nil {
		return m.PolicyId
	}
	return 0
}

type MsgUpdatePolicyAttributes struct {
	Authority  string            `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	PolicyId   uint64            `protobuf:"varint,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Attributes []PolicyAttribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes"`
	Replace    bool              `protobuf:"varint,4,opt,name=replace,proto3" json:"replace,omitempty"`
}

func (m *MsgUpdatePolicyAttributes) Reset()         { *m = MsgUpdatePolicyAttributes{} }
func (m *MsgUpdatePolicyAttributes) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePolicyAttributes) ProtoMessage()    {}
func (*MsgUpdatePolicyAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{2}
}
func (m *MsgUpdatePolicyAttributes) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePolicyAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePolicyAttributes.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePolicyAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePolicyAttributes.Merge(m, src)
}
func (m *MsgUpdatePolicyAttributes) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePolicyAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePolicyAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePolicyAttributes proto.InternalMessageInfo

func (m *MsgUpdatePolicyAttributes) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdatePolicyAttributes) GetPolicyId() uint64 {
	if m != nil {
		return m.PolicyId
	}
	return 0
}

func (m *MsgUpdatePolicyAttributes) GetAttributes() []PolicyAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *MsgUpdatePolicyAttributes) GetReplace() bool {
	if m != nil {
		return m.Replace
	}
	return false
}

type MsgUpdatePolicyAttributesResponse struct {
}

func (m *MsgUpdatePolicyAttributesResponse) Reset()         { *m = MsgUpdatePolicyAttributesResponse{} }
func (m *MsgUpdatePolicyAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePolicyAttributesResponse) ProtoMessage()    {}
func (*MsgUpdatePolicyAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{3}
}
func (m *MsgUpdatePolicyAttributesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePolicyAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePolicyAttributesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePolicyAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePolicyAttributesResponse.Merge(m, src)
}
func (m *MsgUpdatePolicyAttributesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePolicyAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePolicyAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePolicyAttributesResponse proto.InternalMessageInfo

type MsgCancelPolicy struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	PolicyId  uint64 `protobuf:"varint,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Reason    string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgCancelPolicy) Reset()         { *m = MsgCancelPolicy{} }
func (m *MsgCancelPolicy) String() string { return proto.CompactTextString(m) }
func (*MsgCancelPolicy) ProtoMessage()    {}
func (*MsgCancelPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{4}
}
func (m *MsgCancelPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelPolicy.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelPolicy.Merge(m, src)
}
func (m *MsgCancelPolicy) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelPolicy proto.InternalMessageInfo

func (m *MsgCancelPolicy) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCancelPolicy) GetPolicyId() uint64 {
	if m != nil {
		return m.PolicyId
	}
	return 0
}

func (m *MsgCancelPolicy) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type MsgCancelPolicyResponse struct {
}

func (m *MsgCancelPolicyResponse) Reset()         { *m = MsgCancelPolicyResponse{} }
func (m *MsgCancelPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelPolicyResponse) ProtoMessage()    {}
func (*MsgCancelPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{5}
}
func (m *MsgCancelPolicyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelPolicyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelPolicyResponse.Merge(m, src)
}
func (m *MsgCancelPolicyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelPolicyResponse proto.InternalMessageInfo

type MsgUpdatePolicyStatus struct {
	Authority string       `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	PolicyId  uint64       `protobuf:"varint,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Status    PolicyStatus `protobuf:"varint,3,opt,name=status,proto3,enum=osmosis.policy.v1beta1.PolicyStatus" json:"status,omitempty"`
}

func (m *MsgUpdatePolicyStatus) Reset()         { *m = MsgUpdatePolicyStatus{} }
func (m *MsgUpdatePolicyStatus) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePolicyStatus) ProtoMessage()    {}
func (*MsgUpdatePolicyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{6}
}
func (m *MsgUpdatePolicyStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePolicyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePolicyStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePolicyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePolicyStatus.Merge(m, src)
}
func (m *MsgUpdatePolicyStatus) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePolicyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePolicyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePolicyStatus proto.InternalMessageInfo

func (m *MsgUpdatePolicyStatus) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdatePolicyStatus) GetPolicyId() uint64 {
	if m != nil {
		return m.PolicyId
	}
	return 0
}

func (m *MsgUpdatePolicyStatus) GetStatus() PolicyStatus {
	if m != nil {
		return m.Status
	}
	return PolicyStatus_POLICY_STATUS_UNSPECIFIED
}

type MsgUpdatePolicyStatusResponse struct {
}

func (m *MsgUpdatePolicyStatusResponse) Reset()         { *m = MsgUpdatePolicyStatusResponse{} }
func (m *MsgUpdatePolicyStatusResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePolicyStatusResponse) ProtoMessage()    {}
func (*MsgUpdatePolicyStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8774b84512590bb5, []int{7}
}
func (m *MsgUpdatePolicyStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePolicyStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePolicyStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePolicyStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePolicyStatusResponse.Merge(m, src)
}
func (m *MsgUpdatePolicyStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePolicyStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePolicyStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePolicyStatusResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreatePolicy)(nil), "osmosis.policy.v1beta1.MsgCreatePolicy")
	proto.RegisterType((*MsgCreatePolicyResponse)(nil), "osmosis.policy.v1beta1.MsgCreatePolicyResponse")
	proto.RegisterType((*MsgUpdatePolicyAttributes)(nil), "osmosis.policy.v1beta1.MsgUpdatePolicyAttributes")
	proto.RegisterType((*MsgUpdatePolicyAttributesResponse)(nil), "osmosis.policy.v1beta1.MsgUpdatePolicyAttributesResponse")
	proto.RegisterType((*MsgCancelPolicy)(nil), "osmosis.policy.v1beta1.MsgCancelPolicy")
	proto.RegisterType((*MsgCancelPolicyResponse)(nil), "osmosis.policy.v1beta1.MsgCancelPolicyResponse")
	proto.RegisterType((*MsgUpdatePolicyStatus)(nil), "osmosis.policy.v1beta1.MsgUpdatePolicyStatus")
	proto.RegisterType((*MsgUpdatePolicyStatusResponse)(nil), "osmosis.policy.v1beta1.MsgUpdatePolicyStatusResponse")
}

func init() { proto.RegisterFile("osmosis/policy/v1beta1/tx.proto", fileDescriptor_8774b84512590bb5) }

var fileDescriptor_8774b84512590bb5 = []byte{
	// 802 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcf, 0x4f, 0x13, 0x4d,
	0x18, 0xee, 0xb6, 0xa5, 0xd0, 0xe1, 0x0b, 0xdf, 0xf7, 0x6d, 0x10, 0x96, 0x8a, 0x6d, 0x5d, 0x4c,
	0x68, 0x30, 0xdd, 0xb1, 0x25, 0x60, 0x28, 0x26, 0x84, 0x7a, 0x22, 0xb1, 0x09, 0x59, 0xf0, 0xe2,
	0xa5, 0x99, 0x76, 0xc7, 0x65, 0x93, 0x76, 0x67, 0xb3, 0x33, 0x45, 0x1a, 0xe3, 0x85, 0xa3, 0x27,
	0xa2, 0xf1, 0xe2, 0xdd, 0xb3, 0x1c, 0x4c, 0xfc, 0x0f, 0x94, 0x23, 0xd1, 0x8b, 0x27, 0x35, 0xc5,
	0x84, 0x7f, 0xc3, 0xec, 0xcc, 0x6e, 0x5b, 0x4a, 0x5b, 0x20, 0xca, 0xa5, 0xdd, 0x77, 0xe6, 0x79,
	0xde, 0x1f, 0xcf, 0xfb, 0xbe, 0xbb, 0x20, 0x45, 0x68, 0x9d, 0x50, 0x8b, 0x42, 0x87, 0xd4, 0xac,
	0x6a, 0x13, 0xee, 0xe6, 0x2a, 0x98, 0xa1, 0x1c, 0x64, 0x7b, 0x9a, 0xe3, 0x12, 0x46, 0xe4, 0x29,
	0x1f, 0xa0, 0x09, 0x80, 0xe6, 0x03, 0x12, 0xff, 0xa3, 0xba, 0x65, 0x13, 0xc8, 0x7f, 0x05, 0x34,
	0x31, 0x53, 0xe5, 0xd8, 0x32, 0xb7, 0xa0, 0x30, 0xfc, 0xab, 0x69, 0x61, 0xc1, 0x3a, 0x35, 0xe1,
	0x6e, 0xce, 0xfb, 0xf3, 0x2f, 0x66, 0x4d, 0x42, 0xcc, 0x1a, 0x86, 0xc8, 0xb1, 0x20, 0xb2, 0x6d,
	0xc2, 0x10, 0xb3, 0x88, 0x1d, 0xd0, 0x26, 0x4d, 0x62, 0x12, 0xe1, 0xce, 0x7b, 0xf2, 0x4f, 0x53,
	0x3e, 0x87, 0x5b, 0x95, 0xc6, 0x53, 0xc8, 0xac, 0x3a, 0xa6, 0x0c, 0xd5, 0x1d, 0x1f, 0x30, 0x37,
	0xa0, 0x28, 0xbf, 0x04, 0x0e, 0x52, 0xdf, 0x46, 0xc0, 0xbf, 0x25, 0x6a, 0x3e, 0x74, 0x31, 0x62,
	0x78, 0x93, 0xdf, 0xc8, 0x1a, 0x18, 0x21, 0xcf, 0x6c, 0xec, 0x2a, 0x52, 0x5a, 0xca, 0xc4, 0x8b,
	0xca, 0x97, 0x0f, 0xd9, 0x49, 0xbf, 0x8e, 0x75, 0xc3, 0x70, 0x31, 0xa5, 0x5b, 0xcc, 0xb5, 0x6c,
	0x53, 0x17, 0x30, 0x39, 0x05, 0xc6, 0x85, 0xcf, 0x32, 0x6b, 0x3a, 0x58, 0x09, 0x7b, 0x2c, 0x1d,
	0x88, 0xa3, 0xed, 0xa6, 0x83, 0xe5, 0x12, 0x00, 0x88, 0x31, 0xd7, 0xaa, 0x34, 0x18, 0xa6, 0x4a,
	0x24, 0x1d, 0xc9, 0x8c, 0xe7, 0xe7, 0xb5, 0xfe, 0x92, 0x6a, 0x22, 0x89, 0xf5, 0x00, 0x5f, 0x8c,
	0x1e, 0x7d, 0x4f, 0x85, 0xf4, 0x2e, 0x07, 0x72, 0x06, 0xfc, 0xc7, 0x5c, 0x8c, 0x68, 0xc3, 0x6d,
	0x96, 0x1d, 0x42, 0x6a, 0x65, 0xcb, 0x50, 0xa2, 0x3c, 0xe8, 0x44, 0x70, 0xbe, 0x49, 0x48, 0x6d,
	0xc3, 0x90, 0xd7, 0x00, 0xa0, 0x0c, 0xb9, 0xac, 0xec, 0x69, 0xa3, 0x8c, 0xa4, 0xa5, 0xcc, 0x78,
	0x3e, 0xa1, 0x09, 0xe1, 0xb4, 0x40, 0x38, 0x6d, 0x3b, 0x10, 0xae, 0x18, 0x3d, 0xf8, 0x91, 0x92,
	0xf4, 0x38, 0xe7, 0x78, 0xa7, 0xf2, 0x2a, 0x18, 0xc3, 0xb6, 0x21, 0xe8, 0xb1, 0x4b, 0xd2, 0x47,
	0xb1, 0x6d, 0x70, 0xb2, 0x0c, 0xa2, 0x0c, 0x99, 0x54, 0x19, 0x4d, 0x47, 0x32, 0x71, 0x9d, 0x3f,
	0x17, 0xee, 0xee, 0x9f, 0x1e, 0x2e, 0x08, 0xdd, 0x5e, 0x9e, 0x1e, 0x2e, 0xcc, 0xf6, 0xf4, 0xa8,
	0xca, 0xfb, 0x90, 0x15, 0x96, 0xba, 0x0c, 0xa6, 0x7b, 0x7a, 0xa3, 0x63, 0xea, 0x10, 0x9b, 0x62,
	0xf9, 0x26, 0x88, 0xfb, 0x9a, 0x5b, 0x06, 0xef, 0x53, 0x54, 0x1f, 0x13, 0x07, 0x1b, 0x86, 0xfa,
	0x26, 0x0c, 0x66, 0x4a, 0xd4, 0x7c, 0xec, 0x18, 0x6d, 0xe2, 0x7a, 0x47, 0xbe, 0x65, 0x10, 0x47,
	0x0d, 0xb6, 0x43, 0x5c, 0x8b, 0x35, 0x2f, 0x6c, 0x71, 0x07, 0x7a, 0x36, 0x64, 0xf8, 0x6c, 0xc8,
	0xbf, 0xdd, 0x62, 0x05, 0x8c, 0xba, 0xd8, 0xa9, 0xa1, 0x2a, 0xe6, 0x9d, 0x1d, 0xd3, 0x03, 0xb3,
	0x50, 0xf0, 0x04, 0xec, 0x64, 0xe5, 0x89, 0x38, 0xdf, 0x23, 0x62, 0x83, 0xd7, 0xed, 0x8b, 0x98,
	0xed, 0x78, 0x55, 0xe7, 0xc0, 0xed, 0x81, 0xb2, 0x04, 0xca, 0xaa, 0xef, 0x25, 0xb1, 0x11, 0xc8,
	0xae, 0xe2, 0x9a, 0xbf, 0x11, 0xd7, 0x22, 0xd9, 0x14, 0x88, 0x79, 0xd3, 0x4a, 0x6c, 0x25, 0xc2,
	0x87, 0xd7, 0xb7, 0x0a, 0xf0, 0x7c, 0x85, 0xe7, 0xc6, 0x84, 0x27, 0x17, 0x8c, 0xc9, 0x8c, 0x18,
	0x93, 0xae, 0x84, 0xdb, 0xc5, 0xb4, 0x24, 0x70, 0xa3, 0xa7, 0xe4, 0x2d, 0x86, 0x58, 0xe3, 0x9a,
	0xa6, 0xe0, 0x01, 0x88, 0x51, 0xee, 0x9e, 0x97, 0x34, 0x91, 0xbf, 0x33, 0x7c, 0x02, 0x44, 0x2a,
	0xba, 0xcf, 0x29, 0x2c, 0x9f, 0x2f, 0x7c, 0x6e, 0x68, 0x6b, 0x05, 0x4f, 0x4d, 0x81, 0x5b, 0x7d,
	0x6b, 0x0c, 0x54, 0xc8, 0x7f, 0x1a, 0x01, 0x91, 0x12, 0x35, 0xe5, 0x57, 0x12, 0xf8, 0xe7, 0xcc,
	0x9b, 0x6e, 0xe0, 0x84, 0xf6, 0xac, 0x5d, 0x02, 0x5e, 0x12, 0xd8, 0x16, 0x3e, 0xb3, 0xff, 0xf5,
	0xd7, 0xeb, 0xb0, 0xaa, 0xa6, 0xe1, 0xb0, 0xb7, 0xb0, 0x85, 0xa9, 0xfc, 0x59, 0x02, 0x53, 0x03,
	0x36, 0x35, 0x37, 0x24, 0x6a, 0x7f, 0x4a, 0x62, 0xe5, 0xca, 0x94, 0x76, 0xca, 0x6b, 0x3c, 0xe5,
	0x15, 0xf5, 0xfe, 0x45, 0x29, 0xc3, 0xe7, 0xed, 0x09, 0x78, 0x01, 0xbb, 0x96, 0xf6, 0x9d, 0x27,
	0x6f, 0xf7, 0xda, 0x0c, 0x95, 0xb7, 0x0b, 0x38, 0x5c, 0xde, 0x7e, 0x73, 0xbd, 0xca, 0x73, 0x5d,
	0x52, 0x17, 0xaf, 0x94, 0xab, 0x58, 0x1b, 0xf9, 0xa3, 0x04, 0xe4, 0x3e, 0x1b, 0x91, 0xbd, 0xa4,
	0x74, 0x02, 0x9e, 0x58, 0xba, 0x12, 0xfc, 0x0f, 0x33, 0x17, 0x93, 0x5e, 0x7c, 0x74, 0xd4, 0x4a,
	0x4a, 0xc7, 0xad, 0xa4, 0xf4, 0xb3, 0x95, 0x94, 0x0e, 0x4e, 0x92, 0xa1, 0xe3, 0x93, 0x64, 0xe8,
	0xdb, 0x49, 0x32, 0xf4, 0x24, 0x6f, 0x5a, 0x6c, 0xa7, 0x51, 0xd1, 0xaa, 0xa4, 0x1e, 0x38, 0xce,
	0xd6, 0x50, 0x85, 0xb6, 0xa3, 0xec, 0x2e, 0xde, 0x83, 0x7b, 0x41, 0x2c, 0xef, 0x3b, 0x4d, 0x2b,
	0x31, 0xfe, 0x09, 0x5b, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x27, 0xd1, 0x87, 0x69, 0xfe, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreatePolicy(ctx context.Context, in *MsgCreatePolicy, opts ...grpc.CallOption) (*MsgCreatePolicyResponse, error)
	UpdatePolicyAttributes(ctx context.Context, in *MsgUpdatePolicyAttributes, opts ...grpc.CallOption) (*MsgUpdatePolicyAttributesResponse, error)
	CancelPolicy(ctx context.Context, in *MsgCancelPolicy, opts ...grpc.CallOption) (*MsgCancelPolicyResponse, error)
	UpdatePolicyStatus(ctx context.Context, in *MsgUpdatePolicyStatus, opts ...grpc.CallOption) (*MsgUpdatePolicyStatusResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePolicy(ctx context.Context, in *MsgCreatePolicy, opts ...grpc.CallOption) (*MsgCreatePolicyResponse, error) {
	out := new(MsgCreatePolicyResponse)
	err := c.cc.Invoke(ctx, "/osmosis.policy.v1beta1.Msg/CreatePolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePolicyAttributes(ctx context.Context, in *MsgUpdatePolicyAttributes, opts ...grpc.CallOption) (*MsgUpdatePolicyAttributesResponse, error) {
	out := new(MsgUpdatePolicyAttributesResponse)
	err := c.cc.Invoke(ctx, "/osmosis.policy.v1beta1.Msg/UpdatePolicyAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelPolicy(ctx context.Context, in *MsgCancelPolicy, opts ...grpc.CallOption) (*MsgCancelPolicyResponse, error) {
	out := new(MsgCancelPolicyResponse)
	err := c.cc.Invoke(ctx, "/osmosis.policy.v1beta1.Msg/CancelPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePolicyStatus(ctx context.Context, in *MsgUpdatePolicyStatus, opts ...grpc.CallOption) (*MsgUpdatePolicyStatusResponse, error) {
	out := new(MsgUpdatePolicyStatusResponse)
	err := c.cc.Invoke(ctx, "/osmosis.policy.v1beta1.Msg/UpdatePolicyStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreatePolicy(context.Context, *MsgCreatePolicy) (*MsgCreatePolicyResponse, error)
	UpdatePolicyAttributes(context.Context, *MsgUpdatePolicyAttributes) (*MsgUpdatePolicyAttributesResponse, error)
	CancelPolicy(context.Context, *MsgCancelPolicy) (*MsgCancelPolicyResponse, error)
	UpdatePolicyStatus(context.Context, *MsgUpdatePolicyStatus) (*MsgUpdatePolicyStatusResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreatePolicy(ctx context.Context, req *MsgCreatePolicy) (*MsgCreatePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePolicy not implemented")
}
func (*UnimplementedMsgServer) UpdatePolicyAttributes(ctx context.Context, req *MsgUpdatePolicyAttributes) (*MsgUpdatePolicyAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePolicyAttributes not implemented")
}
func (*UnimplementedMsgServer) CancelPolicy(ctx context.Context, req *MsgCancelPolicy) (*MsgCancelPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPolicy not implemented")
}
func (*UnimplementedMsgServer) UpdatePolicyStatus(ctx context.Context, req *MsgUpdatePolicyStatus) (*MsgUpdatePolicyStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePolicyStatus not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.policy.v1beta1.Msg/CreatePolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePolicy(ctx, req.(*MsgCreatePolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePolicyAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePolicyAttributes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePolicyAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.policy.v1beta1.Msg/UpdatePolicyAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePolicyAttributes(ctx, req.(*MsgUpdatePolicyAttributes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.policy.v1beta1.Msg/CancelPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelPolicy(ctx, req.(*MsgCancelPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePolicyStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePolicyStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePolicyStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.policy.v1beta1.Msg/UpdatePolicyStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePolicyStatus(ctx, req.(*MsgUpdatePolicyStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.policy.v1beta1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePolicy",
			Handler:    _Msg_CreatePolicy_Handler,
		},
		{
			MethodName: "UpdatePolicyAttributes",
			Handler:    _Msg_UpdatePolicyAttributes_Handler,
		},
		{
			MethodName: "CancelPolicy",
			Handler:    _Msg_CancelPolicy_Handler,
		},
		{
			MethodName: "UpdatePolicyStatus",
			Handler:    _Msg_UpdatePolicyStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/policy/v1beta1/tx.proto",
}

func (m *MsgCreatePolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tags) > 0 {
		for iNdEx := len(m.Tags) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Tags[iNdEx])
			copy(dAtA[i:], m.Tags[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Tags[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.EndTime != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.EndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EndTime):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintTx(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x32
	}
	if m.StartTime != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.StartTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StartTime):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintTx(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TreasuryPoolId) > 0 {
		i -= len(m.TreasuryPoolId)
		copy(dAtA[i:], m.TreasuryPoolId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TreasuryPoolId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Attributes) > 0 {
		for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PolicyType) > 0 {
		i -= len(m.PolicyType)
		copy(dAtA[i:], m.PolicyType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PolicyType)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePolicyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePolicyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePolicyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PolicyId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PolicyId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePolicyAttributes) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePolicyAttributes) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePolicyAttributes) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Replace {
		i--
		if m.Replace {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.Attributes) > 0 {
		for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.PolicyId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PolicyId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePolicyAttributesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePolicyAttributesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePolicyAttributesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if m.PolicyId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PolicyId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelPolicyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelPolicyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelPolicyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePolicyStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePolicyStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePolicyStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	if m.PolicyId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PolicyId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePolicyStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePolicyStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePolicyStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreatePolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PolicyType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Attributes) > 0 {
		for _, e := range m.Attributes {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.TreasuryPoolId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.StartTime)
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EndTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EndTime)
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Tags) > 0 {
		for _, s := range m.Tags {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgCreatePolicyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PolicyId != 0 {
		n += 1 + sovTx(uint64(m.PolicyId))
	}
	return n
}

func (m *MsgUpdatePolicyAttributes) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PolicyId != 0 {
		n += 1 + sovTx(uint64(m.PolicyId))
	}
	if len(m.Attributes) > 0 {
		for _, e := range m.Attributes {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.Replace {
		n += 2
	}
	return n
}

func (m *MsgUpdatePolicyAttributesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PolicyId != 0 {
		n += 1 + sovTx(uint64(m.PolicyId))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelPolicyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdatePolicyStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PolicyId != 0 {
		n += 1 + sovTx(uint64(m.PolicyId))
	}
	if m.Status != 0 {
		n += 1 + sovTx(uint64(m.Status))
	}
	return n
}

func (m *MsgUpdatePolicyStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreatePolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PolicyType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, PolicyAttribute{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreasuryPoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreasuryPoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartTime == nil {
				m.StartTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndTime == nil {
				m.EndTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tags", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tags = append(m.Tags, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePolicyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePolicyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePolicyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			m.PolicyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePolicyAttributes) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePolicyAttributes: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePolicyAttributes: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			m.PolicyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attributes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, PolicyAttribute{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replace", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Replace = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePolicyAttributesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePolicyAttributesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePolicyAttributesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			m.PolicyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelPolicyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelPolicyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelPolicyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePolicyStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePolicyStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePolicyStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PolicyId", wireType)
			}
			m.PolicyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PolicyId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PolicyStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePolicyStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePolicyStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePolicyStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
