// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: mychain/oracle/v1/oracle.proto

package types

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"
)

// Gateway bindings are currently omitted for the oracle module. The generated
// helpers are stubbed out to satisfy linker expectations.

func RegisterQueryHandlerServer(context.Context, *runtime.ServeMux, QueryServer) error {
	return nil
}

func RegisterQueryHandler(context.Context, *runtime.ServeMux, *grpc.ClientConn) error {
	return nil
}

func RegisterQueryHandlerClient(context.Context, *runtime.ServeMux, QueryClient) error {
	return nil
}

func RegisterQueryHandlerFromEndpoint(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error {
	return nil
}

func RegisterMsgHandlerServer(context.Context, *runtime.ServeMux, MsgServer) error {
	return nil
}

func RegisterMsgHandler(context.Context, *runtime.ServeMux, *grpc.ClientConn) error {
	return nil
}

func RegisterMsgHandlerClient(context.Context, *runtime.ServeMux, MsgClient) error {
	return nil
}

func RegisterMsgHandlerFromEndpoint(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error {
	return nil
}
