package types

const (
	EventTypeBuy              = "buy_from_curve"
	EventTypeSell             = "sell_to_curve"
	EventTypeOpenMargin       = "open_margin_position"
	EventTypeCloseMargin      = "close_margin_position"
	EventTypeCircuitBreaker   = "margin_circuit_breaker"
	EventTypeLiquidationBatch = "margin_liquidation_batch"
	EventTypeLiquidationAlert = "margin_liquidation_alert"
	EventTypePriceVolatility  = "margin_price_volatility"
	EventTypeParamsQueued     = "bondingcurve_params_queued"
	EventTypeParamsApplied    = "bondingcurve_params_applied"
	EventTypeGlobalPause      = "bondingcurve_global_pause"
	EventTypeTokenPause       = "bondingcurve_token_pause"
	EventTypeForceLiquidation = "bondingcurve_force_liquidation"
	EventTypeFreeze           = "bondingcurve_freeze"

	AttributeKeyTrader             = "trader"
	AttributeKeyDenom              = "denom"
	AttributeKeyPaymentDenom       = "payment_denom"
	AttributeKeyPaymentAmount      = "payment_amount"
	AttributeKeyTokensOut          = "tokens_out"
	AttributeKeyTokensIn           = "tokens_in"
	AttributeKeyPaymentOut         = "payment_out"
	AttributeKeyPrice              = "price"
	AttributeKeyCollateralDenom    = "collateral_denom"
	AttributeKeyCollateralAmount   = "collateral_amount"
	AttributeKeyLeverage           = "leverage"
	AttributeKeyPositionSize       = "position_size"
	AttributeKeyEntryPrice         = "entry_price"
	AttributeKeyLiquidationPrice   = "liquidation_price"
	AttributeKeyPositionId         = "position_id"
	AttributeKeyPayoutAmount       = "payout_amount"
	AttributeKeyRealizedPnL        = "realized_pnl"
	AttributeKeyFeesPaid           = "fees_paid"
	AttributeKeyLiquidationPenalty = "liquidation_penalty"
	AttributeKeyLiquidator         = "liquidator"
	AttributeKeyLiquidatorReward   = "liquidator_reward"
	AttributeKeyInsurancePayout    = "insurance_payout"
	AttributeKeyLiquidationType    = "liquidation_type"
	AttributeKeyBadDebtCovered     = "bad_debt_covered"
	AttributeKeyPaused             = "paused"
	AttributeKeyResumeHeight       = "resume_height"
	AttributeKeyPositionsProcessed = "positions_processed"
	AttributeKeyVolatility         = "volatility"
	AttributeKeyThreshold          = "threshold"
	AttributeKeyAuthority          = "authority"
	AttributeKeyReason             = "reason"
	AttributeKeyResumeTime         = "resume_time"
	AttributeKeyExecuteTime        = "execute_time"
	AttributeKeyActionId           = "action_id"
	AttributeKeyTarget             = "target"
	AttributeKeyFrozen             = "frozen"
)
