// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/bondingcurve/v1beta1/margin.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PositionType int32

const (
	PositionType_POSITION_TYPE_UNSPECIFIED PositionType = 0
	PositionType_POSITION_TYPE_LONG        PositionType = 1
	PositionType_POSITION_TYPE_SHORT       PositionType = 2
)

var PositionType_name = map[int32]string{
	0: "POSITION_TYPE_UNSPECIFIED",
	1: "POSITION_TYPE_LONG",
	2: "POSITION_TYPE_SHORT",
}

var PositionType_value = map[string]int32{
	"POSITION_TYPE_UNSPECIFIED": 0,
	"POSITION_TYPE_LONG":        1,
	"POSITION_TYPE_SHORT":       2,
}

func (x PositionType) String() string {
	return proto.EnumName(PositionType_name, int32(x))
}

func (PositionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2ae023b14e67f17, []int{0}
}

type PositionStatus int32

const (
	PositionStatus_POSITION_STATUS_UNSPECIFIED PositionStatus = 0
	PositionStatus_POSITION_STATUS_OPEN        PositionStatus = 1
	PositionStatus_POSITION_STATUS_CLOSED      PositionStatus = 2
	PositionStatus_POSITION_STATUS_LIQUIDATED  PositionStatus = 3
)

var PositionStatus_name = map[int32]string{
	0: "POSITION_STATUS_UNSPECIFIED",
	1: "POSITION_STATUS_OPEN",
	2: "POSITION_STATUS_CLOSED",
	3: "POSITION_STATUS_LIQUIDATED",
}

var PositionStatus_value = map[string]int32{
	"POSITION_STATUS_UNSPECIFIED": 0,
	"POSITION_STATUS_OPEN":        1,
	"POSITION_STATUS_CLOSED":      2,
	"POSITION_STATUS_LIQUIDATED":  3,
}

func (x PositionStatus) String() string {
	return proto.EnumName(PositionStatus_name, int32(x))
}

func (PositionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2ae023b14e67f17, []int{1}
}

type PriceSource int32

const (
	PriceSource_PRICE_SOURCE_UNSPECIFIED   PriceSource = 0
	PriceSource_PRICE_SOURCE_BONDING_CURVE PriceSource = 1
	PriceSource_PRICE_SOURCE_DEX_POOL      PriceSource = 2
)

var PriceSource_name = map[int32]string{
	0: "PRICE_SOURCE_UNSPECIFIED",
	1: "PRICE_SOURCE_BONDING_CURVE",
	2: "PRICE_SOURCE_DEX_POOL",
}

var PriceSource_value = map[string]int32{
	"PRICE_SOURCE_UNSPECIFIED":   0,
	"PRICE_SOURCE_BONDING_CURVE": 1,
	"PRICE_SOURCE_DEX_POOL":      2,
}

func (x PriceSource) String() string {
	return proto.EnumName(PriceSource_name, int32(x))
}

func (PriceSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2ae023b14e67f17, []int{2}
}

type MarginPosition struct {
	Id                uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Trader            string         `protobuf:"bytes,2,opt,name=trader,proto3" json:"trader,omitempty"`
	Denom             string         `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	CollateralDenom   string         `protobuf:"bytes,4,opt,name=collateral_denom,json=collateralDenom,proto3" json:"collateral_denom,omitempty"`
	CollateralAmount  string         `protobuf:"bytes,5,opt,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount,omitempty"`
	PositionSize      string         `protobuf:"bytes,6,opt,name=position_size,json=positionSize,proto3" json:"position_size,omitempty"`
	EntryPrice        string         `protobuf:"bytes,7,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	Leverage          uint32         `protobuf:"varint,8,opt,name=leverage,proto3" json:"leverage,omitempty"`
	Type              PositionType   `protobuf:"varint,9,opt,name=type,proto3,enum=osmosis.bondingcurve.v1beta1.PositionType" json:"type,omitempty"`
	CreatedAt         uint64         `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LiquidationPrice  string         `protobuf:"bytes,11,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	MaintenanceMargin string         `protobuf:"bytes,12,opt,name=maintenance_margin,json=maintenanceMargin,proto3" json:"maintenance_margin,omitempty"`
	FundingFeeAccrued string         `protobuf:"bytes,13,opt,name=funding_fee_accrued,json=fundingFeeAccrued,proto3" json:"funding_fee_accrued,omitempty"`
	Status            PositionStatus `protobuf:"varint,14,opt,name=status,proto3,enum=osmosis.bondingcurve.v1beta1.PositionStatus" json:"status,omitempty"`
	RealizedPnl       string         `protobuf:"bytes,15,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	LastMarkPrice     string         `protobuf:"bytes,16,opt,name=last_mark_price,json=lastMarkPrice,proto3" json:"last_mark_price,omitempty"`
	PriceSource       PriceSource    `protobuf:"varint,17,opt,name=price_source,json=priceSource,proto3,enum=osmosis.bondingcurve.v1beta1.PriceSource" json:"price_source,omitempty"`
}

func (m *MarginPosition) Reset()         { *m = MarginPosition{} }
func (m *MarginPosition) String() string { return proto.CompactTextString(m) }
func (*MarginPosition) ProtoMessage()    {}
func (*MarginPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2ae023b14e67f17, []int{0}
}
func (m *MarginPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarginPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarginPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarginPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarginPosition.Merge(m, src)
}
func (m *MarginPosition) XXX_Size() int {
	return m.Size()
}
func (m *MarginPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_MarginPosition.DiscardUnknown(m)
}

var xxx_messageInfo_MarginPosition proto.InternalMessageInfo

func (m *MarginPosition) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MarginPosition) GetTrader() string {
	if m != nil {
		return m.Trader
	}
	return ""
}

func (m *MarginPosition) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MarginPosition) GetCollateralDenom() string {
	if m != nil {
		return m.CollateralDenom
	}
	return ""
}

func (m *MarginPosition) GetCollateralAmount() string {
	if m != nil {
		return m.CollateralAmount
	}
	return ""
}

func (m *MarginPosition) GetPositionSize() string {
	if m != nil {
		return m.PositionSize
	}
	return ""
}

func (m *MarginPosition) GetEntryPrice() string {
	if m != nil {
		return m.EntryPrice
	}
	return ""
}

func (m *MarginPosition) GetLeverage() uint32 {
	if m != nil {
		return m.Leverage
	}
	return 0
}

func (m *MarginPosition) GetType() PositionType {
	if m != nil {
		return m.Type
	}
	return PositionType_POSITION_TYPE_UNSPECIFIED
}

func (m *MarginPosition) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *MarginPosition) GetLiquidationPrice() string {
	if m != nil {
		return m.LiquidationPrice
	}
	return ""
}

func (m *MarginPosition) GetMaintenanceMargin() string {
	if m != nil {
		return m.MaintenanceMargin
	}
	return ""
}

func (m *MarginPosition) GetFundingFeeAccrued() string {
	if m != nil {
		return m.FundingFeeAccrued
	}
	return ""
}

func (m *MarginPosition) GetStatus() PositionStatus {
	if m != nil {
		return m.Status
	}
	return PositionStatus_POSITION_STATUS_UNSPECIFIED
}

func (m *MarginPosition) GetRealizedPnl() string {
	if m != nil {
		return m.RealizedPnl
	}
	return ""
}

func (m *MarginPosition) GetLastMarkPrice() string {
	if m != nil {
		return m.LastMarkPrice
	}
	return ""
}

func (m *MarginPosition) GetPriceSource() PriceSource {
	if m != nil {
		return m.PriceSource
	}
	return PriceSource_PRICE_SOURCE_UNSPECIFIED
}

type MarginPool struct {
	Denom                  string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	TotalCollateral        string `protobuf:"bytes,2,opt,name=total_collateral,json=totalCollateral,proto3" json:"total_collateral,omitempty"`
	AvailableLiquidity     string `protobuf:"bytes,3,opt,name=available_liquidity,json=availableLiquidity,proto3" json:"available_liquidity,omitempty"`
	TotalLongExposure      string `protobuf:"bytes,4,opt,name=total_long_exposure,json=totalLongExposure,proto3" json:"total_long_exposure,omitempty"`
	TotalShortExposure     string `protobuf:"bytes,5,opt,name=total_short_exposure,json=totalShortExposure,proto3" json:"total_short_exposure,omitempty"`
	MaintenanceMarginRatio string `protobuf:"bytes,6,opt,name=maintenance_margin_ratio,json=maintenanceMarginRatio,proto3" json:"maintenance_margin_ratio,omitempty"`
	NextPositionId         uint64 `protobuf:"varint,7,opt,name=next_position_id,json=nextPositionId,proto3" json:"next_position_id,omitempty"`
	LastFundingTimestamp   uint64 `protobuf:"varint,8,opt,name=last_funding_timestamp,json=lastFundingTimestamp,proto3" json:"last_funding_timestamp,omitempty"`
	CumulativeFundingRate  string `protobuf:"bytes,9,opt,name=cumulative_funding_rate,json=cumulativeFundingRate,proto3" json:"cumulative_funding_rate,omitempty"`
	InsuranceFund          string `protobuf:"bytes,10,opt,name=insurance_fund,json=insuranceFund,proto3" json:"insurance_fund,omitempty"`
	TotalLiquidationFees   string `protobuf:"bytes,11,opt,name=total_liquidation_fees,json=totalLiquidationFees,proto3" json:"total_liquidation_fees,omitempty"`
	TotalBadDebt           string `protobuf:"bytes,12,opt,name=total_bad_debt,json=totalBadDebt,proto3" json:"total_bad_debt,omitempty"`
	LiquidationsPaused     bool   `protobuf:"varint,13,opt,name=liquidations_paused,json=liquidationsPaused,proto3" json:"liquidations_paused,omitempty"`
	LastMarkPrice          string `protobuf:"bytes,14,opt,name=last_mark_price,json=lastMarkPrice,proto3" json:"last_mark_price,omitempty"`
	LastTwapPrice          string `protobuf:"bytes,15,opt,name=last_twap_price,json=lastTwapPrice,proto3" json:"last_twap_price,omitempty"`
	TotalLiquidations      uint64 `protobuf:"varint,16,opt,name=total_liquidations,json=totalLiquidations,proto3" json:"total_liquidations,omitempty"`
	LastLiquidationHeight  uint64 `protobuf:"varint,17,opt,name=last_liquidation_height,json=lastLiquidationHeight,proto3" json:"last_liquidation_height,omitempty"`
}

func (m *MarginPool) Reset()         { *m = MarginPool{} }
func (m *MarginPool) String() string { return proto.CompactTextString(m) }
func (*MarginPool) ProtoMessage()    {}
func (*MarginPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2ae023b14e67f17, []int{1}
}
func (m *MarginPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MarginPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MarginPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MarginPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarginPool.Merge(m, src)
}
func (m *MarginPool) XXX_Size() int {
	return m.Size()
}
func (m *MarginPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MarginPool.DiscardUnknown(m)
}

var xxx_messageInfo_MarginPool proto.InternalMessageInfo

func (m *MarginPool) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *MarginPool) GetTotalCollateral() string {
	if m != nil {
		return m.TotalCollateral
	}
	return ""
}

func (m *MarginPool) GetAvailableLiquidity() string {
	if m != nil {
		return m.AvailableLiquidity
	}
	return ""
}

func (m *MarginPool) GetTotalLongExposure() string {
	if m != nil {
		return m.TotalLongExposure
	}
	return ""
}

func (m *MarginPool) GetTotalShortExposure() string {
	if m != nil {
		return m.TotalShortExposure
	}
	return ""
}

func (m *MarginPool) GetMaintenanceMarginRatio() string {
	if m != nil {
		return m.MaintenanceMarginRatio
	}
	return ""
}

func (m *MarginPool) GetNextPositionId() uint64 {
	if m != nil {
		return m.NextPositionId
	}
	return 0
}

func (m *MarginPool) GetLastFundingTimestamp() uint64 {
	if m != nil {
		return m.LastFundingTimestamp
	}
	return 0
}

func (m *MarginPool) GetCumulativeFundingRate() string {
	if m != nil {
		return m.CumulativeFundingRate
	}
	return ""
}

func (m *MarginPool) GetInsuranceFund() string {
	if m != nil {
		return m.InsuranceFund
	}
	return ""
}

func (m *MarginPool) GetTotalLiquidationFees() string {
	if m != nil {
		return m.TotalLiquidationFees
	}
	return ""
}

func (m *MarginPool) GetTotalBadDebt() string {
	if m != nil {
		return m.TotalBadDebt
	}
	return ""
}

func (m *MarginPool) GetLiquidationsPaused() bool {
	if m != nil {
		return m.LiquidationsPaused
	}
	return false
}

func (m *MarginPool) GetLastMarkPrice() string {
	if m != nil {
		return m.LastMarkPrice
	}
	return ""
}

func (m *MarginPool) GetLastTwapPrice() string {
	if m != nil {
		return m.LastTwapPrice
	}
	return ""
}

func (m *MarginPool) GetTotalLiquidations() uint64 {
	if m != nil {
		return m.TotalLiquidations
	}
	return 0
}

func (m *MarginPool) GetLastLiquidationHeight() uint64 {
	if m != nil {
		return m.LastLiquidationHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("osmosis.bondingcurve.v1beta1.PositionType", PositionType_name, PositionType_value)
	proto.RegisterEnum("osmosis.bondingcurve.v1beta1.PositionStatus", PositionStatus_name, PositionStatus_value)
	proto.RegisterEnum("osmosis.bondingcurve.v1beta1.PriceSource", PriceSource_name, PriceSource_value)
	proto.RegisterType((*MarginPosition)(nil), "osmosis.bondingcurve.v1beta1.MarginPosition")
	proto.RegisterType((*MarginPool)(nil), "osmosis.bondingcurve.v1beta1.MarginPool")
}

func init() {
	proto.RegisterFile("osmosis/bondingcurve/v1beta1/margin.proto", fileDescriptor_a2ae023b14e67f17)
}

var fileDescriptor_a2ae023b14e67f17 = []byte{
	// 1019 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x17, 0x35, 0x15, 0xd9, 0x9f, 0x7d, 0x2d, 0xcb, 0xf4, 0xf8, 0x27, 0x8c, 0xbf, 0x44, 0x71, 0xd3,
	0x1f, 0xd8, 0x6e, 0x23, 0x25, 0x4d, 0x51, 0x64, 0x55, 0xc0, 0x96, 0xe4, 0x44, 0x80, 0x22, 0xa9,
	0xa4, 0x5c, 0xb4, 0x5d, 0x74, 0x30, 0x12, 0xaf, 0xe5, 0x41, 0x28, 0x92, 0x25, 0x87, 0x8a, 0xed,
	0x17, 0xe8, 0xb6, 0x2f, 0xd0, 0xf7, 0xe9, 0x32, 0xe8, 0xaa, 0xcb, 0xc2, 0x7e, 0x91, 0x62, 0x86,
	0x43, 0x89, 0x96, 0x83, 0xb6, 0x3b, 0xcd, 0x39, 0xe7, 0x8e, 0xee, 0xdf, 0x19, 0xc2, 0x41, 0x10,
	0x8f, 0x83, 0x98, 0xc7, 0xb5, 0x41, 0xe0, 0xbb, 0xdc, 0x1f, 0x0d, 0x93, 0x68, 0x82, 0xb5, 0xc9,
	0xf3, 0x01, 0x0a, 0xf6, 0xbc, 0x36, 0x66, 0xd1, 0x88, 0xfb, 0xd5, 0x30, 0x0a, 0x44, 0x40, 0x1e,
	0x6a, 0x69, 0x35, 0x2f, 0xad, 0x6a, 0xe9, 0xee, 0xd6, 0x28, 0x18, 0x05, 0x4a, 0x58, 0x93, 0xbf,
	0xd2, 0x98, 0x27, 0x7f, 0x2c, 0x42, 0xf9, 0x8d, 0xba, 0xa4, 0x17, 0xc4, 0x5c, 0xf0, 0xc0, 0x27,
	0x65, 0x28, 0x70, 0xd7, 0x32, 0xf6, 0x8c, 0xfd, 0xa2, 0x5d, 0xe0, 0x2e, 0xd9, 0x81, 0x25, 0x11,
	0x31, 0x17, 0x23, 0xab, 0xb0, 0x67, 0xec, 0xaf, 0xd8, 0xfa, 0x44, 0xb6, 0x60, 0xd1, 0x45, 0x3f,
	0x18, 0x5b, 0xf7, 0x14, 0x9c, 0x1e, 0xc8, 0x01, 0x98, 0xc3, 0xc0, 0xf3, 0x98, 0xc0, 0x88, 0x79,
	0x34, 0x15, 0x14, 0x95, 0x60, 0x7d, 0x86, 0x37, 0x94, 0xf4, 0x73, 0xd8, 0xc8, 0x49, 0xd9, 0x38,
	0x48, 0x7c, 0x61, 0x2d, 0x2a, 0x6d, 0xee, 0x8e, 0x23, 0x85, 0x93, 0x8f, 0x61, 0x2d, 0xd4, 0x19,
	0xd2, 0x98, 0x5f, 0xa1, 0xb5, 0xa4, 0x84, 0xa5, 0x0c, 0x74, 0xf8, 0x15, 0x92, 0xc7, 0xb0, 0x8a,
	0xbe, 0x88, 0x2e, 0x69, 0x18, 0xf1, 0x21, 0x5a, 0xff, 0x53, 0x12, 0x50, 0x50, 0x4f, 0x22, 0x64,
	0x17, 0x96, 0x3d, 0x9c, 0x60, 0xc4, 0x46, 0x68, 0x2d, 0xef, 0x19, 0xfb, 0x6b, 0xf6, 0xf4, 0x4c,
	0xbe, 0x81, 0xa2, 0xb8, 0x0c, 0xd1, 0x5a, 0xd9, 0x33, 0xf6, 0xcb, 0x5f, 0x1e, 0x56, 0xff, 0xa9,
	0x9b, 0xd5, 0xac, 0x5b, 0xfd, 0xcb, 0x10, 0x6d, 0x15, 0x47, 0x1e, 0x01, 0x0c, 0x23, 0x64, 0x02,
	0x5d, 0xca, 0x84, 0x05, 0xaa, 0x7f, 0x2b, 0x1a, 0x39, 0x12, 0xb2, 0x5a, 0x8f, 0xff, 0x9c, 0x70,
	0x97, 0xa9, 0x1a, 0xd2, 0x0c, 0x57, 0xd3, 0x6a, 0x73, 0x44, 0x9a, 0xe7, 0x53, 0x20, 0x63, 0xc6,
	0x7d, 0x81, 0x3e, 0xf3, 0x87, 0x48, 0xd3, 0x31, 0x5b, 0x25, 0xa5, 0xde, 0xc8, 0x31, 0xe9, 0xe8,
	0x48, 0x15, 0x36, 0xcf, 0x12, 0x95, 0x25, 0x3d, 0x43, 0xa4, 0x6c, 0x38, 0x8c, 0x12, 0x74, 0xad,
	0xb5, 0x54, 0xaf, 0xa9, 0x13, 0xc4, 0xa3, 0x94, 0x20, 0x0d, 0x58, 0x8a, 0x05, 0x13, 0x49, 0x6c,
	0x95, 0x55, 0xb1, 0x5f, 0xfc, 0xb7, 0x62, 0x1d, 0x15, 0x63, 0xeb, 0x58, 0xf2, 0x11, 0x94, 0x22,
	0x64, 0x1e, 0xbf, 0x42, 0x97, 0x86, 0xbe, 0x67, 0xad, 0xab, 0xbf, 0x5b, 0xcd, 0xb0, 0x9e, 0xef,
	0x91, 0xcf, 0x60, 0xdd, 0x63, 0xb1, 0x90, 0x05, 0xbc, 0xd5, 0x25, 0x9b, 0x4a, 0xb5, 0x26, 0xe1,
	0x37, 0x2c, 0x7a, 0x9b, 0xd6, 0xdb, 0x86, 0x92, 0x62, 0x69, 0x1c, 0x24, 0xd1, 0x10, 0xad, 0x0d,
	0x95, 0xd6, 0xc1, 0xbf, 0xa4, 0x25, 0x23, 0x1c, 0x15, 0x60, 0xaf, 0x86, 0xb3, 0xc3, 0x93, 0xdf,
	0x96, 0x00, 0xb2, 0xa5, 0x0e, 0xbc, 0xd9, 0xa2, 0x1a, 0x73, 0x8b, 0x2a, 0x02, 0xc1, 0x3c, 0x3a,
	0x5b, 0x35, 0xbd, 0xe0, 0xeb, 0x0a, 0xaf, 0x4f, 0x61, 0x52, 0x83, 0x4d, 0x36, 0x61, 0xdc, 0x63,
	0x03, 0x0f, 0x69, 0x3a, 0x2b, 0x2e, 0x2e, 0xf5, 0xde, 0x93, 0x29, 0xd5, 0xce, 0x18, 0x39, 0x8f,
	0xf4, 0x6e, 0x2f, 0xf0, 0x47, 0x14, 0x2f, 0xc2, 0x20, 0x4e, 0x22, 0xd4, 0x3e, 0xd8, 0x50, 0x54,
	0x3b, 0xf0, 0x47, 0x4d, 0x4d, 0x90, 0x67, 0xb0, 0x95, 0xea, 0xe3, 0xf3, 0x20, 0x12, 0xb3, 0x80,
	0xd4, 0x0c, 0x44, 0x71, 0x8e, 0xa4, 0xa6, 0x11, 0x2f, 0xc1, 0xba, 0xbb, 0x20, 0x34, 0x92, 0x2b,
	0xa4, 0x9d, 0xb1, 0x73, 0x67, 0x4d, 0x6c, 0xc9, 0x92, 0x7d, 0x30, 0x7d, 0xbc, 0x10, 0x74, 0xea,
	0x26, 0xee, 0x2a, 0xa3, 0x14, 0xed, 0xb2, 0xc4, 0xb3, 0x59, 0xb7, 0x5c, 0xf2, 0x15, 0xec, 0xa8,
	0xe1, 0x65, 0xab, 0x25, 0xf8, 0x18, 0x63, 0xc1, 0xc6, 0xa1, 0xb2, 0x4e, 0xd1, 0xde, 0x92, 0xec,
	0x49, 0x4a, 0xf6, 0x33, 0x8e, 0x7c, 0x0d, 0xf7, 0x87, 0xc9, 0x38, 0xf1, 0x98, 0xe0, 0x13, 0x9c,
	0xc6, 0x46, 0x4c, 0xa4, 0xce, 0x5a, 0xb1, 0xb7, 0x67, 0xb4, 0x0e, 0xb6, 0x99, 0x40, 0xf2, 0x29,
	0x94, 0xb9, 0x1f, 0x27, 0x91, 0xaa, 0x47, 0x86, 0x29, 0x0b, 0xad, 0xd8, 0x6b, 0x53, 0x54, 0xaa,
	0x65, 0x52, 0xba, 0xb5, 0x39, 0x33, 0x9d, 0x21, 0xc6, 0xda, 0x4b, 0x69, 0x23, 0xdb, 0x33, 0xf2,
	0x04, 0x31, 0x26, 0x9f, 0x40, 0x39, 0x8d, 0x1a, 0x30, 0x97, 0xba, 0x38, 0x10, 0xda, 0x4b, 0x25,
	0x85, 0x1e, 0x33, 0xb7, 0x81, 0x03, 0x21, 0xe7, 0x9c, 0xbb, 0x35, 0xa6, 0x21, 0x4b, 0x62, 0x6d,
	0xa3, 0x65, 0x9b, 0xe4, 0xa9, 0x9e, 0x62, 0x3e, 0xb4, 0xde, 0xe5, 0x0f, 0xad, 0x77, 0xa6, 0x13,
	0xef, 0x58, 0xa8, 0x75, 0xeb, 0x33, 0x5d, 0xff, 0x1d, 0x0b, 0xa7, 0xb6, 0xbf, 0x53, 0x5c, 0xac,
	0x1c, 0x53, 0xcc, 0xd6, 0x26, 0x47, 0xc8, 0x56, 0xab, 0x6b, 0xf3, 0xad, 0x38, 0x47, 0x3e, 0x3a,
	0x17, 0xca, 0x40, 0x45, 0x7b, 0x5b, 0xd2, 0xb9, 0x90, 0xd7, 0x8a, 0x3c, 0xfc, 0x09, 0x4a, 0xf9,
	0xf7, 0x8b, 0x3c, 0x82, 0x07, 0xbd, 0xae, 0xd3, 0xea, 0xb7, 0xba, 0x1d, 0xda, 0xff, 0xa1, 0xd7,
	0xa4, 0xa7, 0x1d, 0xa7, 0xd7, 0xac, 0xb7, 0x4e, 0x5a, 0xcd, 0x86, 0xb9, 0x40, 0x76, 0x80, 0xdc,
	0xa6, 0xdb, 0xdd, 0xce, 0x2b, 0xd3, 0x20, 0xf7, 0x61, 0xf3, 0x36, 0xee, 0xbc, 0xee, 0xda, 0x7d,
	0xb3, 0x70, 0xf8, 0x8b, 0x01, 0xe5, 0xdb, 0x6f, 0x06, 0x79, 0x0c, 0xff, 0x9f, 0x6a, 0x9d, 0xfe,
	0x51, 0xff, 0xd4, 0x99, 0xfb, 0x13, 0x0b, 0xb6, 0xe6, 0x05, 0xdd, 0x5e, 0xb3, 0x63, 0x1a, 0x64,
	0x17, 0x76, 0xe6, 0x99, 0x7a, 0xbb, 0xeb, 0x34, 0x1b, 0x66, 0x81, 0x54, 0x60, 0x77, 0x9e, 0x6b,
	0xb7, 0xbe, 0x3d, 0x6d, 0x35, 0x8e, 0xfa, 0xcd, 0x86, 0x79, 0xef, 0xf0, 0x0c, 0x56, 0x73, 0xaf,
	0x04, 0x79, 0x08, 0x56, 0xcf, 0x6e, 0xd5, 0x9b, 0xd4, 0xe9, 0x9e, 0xda, 0xf5, 0xf9, 0x3a, 0xe5,
	0x65, 0x79, 0xf6, 0xb8, 0xdb, 0x69, 0xb4, 0x3a, 0xaf, 0x68, 0xfd, 0xd4, 0xfe, 0xae, 0x69, 0x1a,
	0xe4, 0x01, 0x6c, 0xdf, 0xe2, 0x1b, 0xcd, 0xef, 0x69, 0xaf, 0xdb, 0x6d, 0x9b, 0x85, 0x63, 0xfb,
	0xf7, 0xeb, 0x8a, 0xf1, 0xfe, 0xba, 0x62, 0xfc, 0x75, 0x5d, 0x31, 0x7e, 0xbd, 0xa9, 0x2c, 0xbc,
	0xbf, 0xa9, 0x2c, 0xfc, 0x79, 0x53, 0x59, 0xf8, 0xf1, 0xe5, 0x88, 0x8b, 0xf3, 0x64, 0x50, 0x1d,
	0x06, 0xe3, 0x9a, 0x7e, 0xcd, 0x9e, 0x7a, 0x6c, 0x10, 0x67, 0x87, 0xda, 0xe4, 0xc5, 0xb3, 0xda,
	0xc5, 0xed, 0xaf, 0xbb, 0xfc, 0x9c, 0xc4, 0x83, 0x25, 0xf5, 0x85, 0x7e, 0xf1, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3d, 0x96, 0x61, 0xd6, 0x02, 0x08, 0x00, 0x00,
}

func (m *MarginPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarginPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarginPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PriceSource != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.PriceSource))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if len(m.LastMarkPrice) > 0 {
		i -= len(m.LastMarkPrice)
		copy(dAtA[i:], m.LastMarkPrice)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.LastMarkPrice)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if len(m.RealizedPnl) > 0 {
		i -= len(m.RealizedPnl)
		copy(dAtA[i:], m.RealizedPnl)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.RealizedPnl)))
		i--
		dAtA[i] = 0x7a
	}
	if m.Status != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x70
	}
	if len(m.FundingFeeAccrued) > 0 {
		i -= len(m.FundingFeeAccrued)
		copy(dAtA[i:], m.FundingFeeAccrued)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.FundingFeeAccrued)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.MaintenanceMargin) > 0 {
		i -= len(m.MaintenanceMargin)
		copy(dAtA[i:], m.MaintenanceMargin)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.MaintenanceMargin)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.LiquidationPrice) > 0 {
		i -= len(m.LiquidationPrice)
		copy(dAtA[i:], m.LiquidationPrice)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.LiquidationPrice)))
		i--
		dAtA[i] = 0x5a
	}
	if m.CreatedAt != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x50
	}
	if m.Type != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x48
	}
	if m.Leverage != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.Leverage))
		i--
		dAtA[i] = 0x40
	}
	if len(m.EntryPrice) > 0 {
		i -= len(m.EntryPrice)
		copy(dAtA[i:], m.EntryPrice)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.EntryPrice)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.PositionSize) > 0 {
		i -= len(m.PositionSize)
		copy(dAtA[i:], m.PositionSize)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.PositionSize)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CollateralAmount) > 0 {
		i -= len(m.CollateralAmount)
		copy(dAtA[i:], m.CollateralAmount)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.CollateralAmount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CollateralDenom) > 0 {
		i -= len(m.CollateralDenom)
		copy(dAtA[i:], m.CollateralDenom)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.CollateralDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Trader) > 0 {
		i -= len(m.Trader)
		copy(dAtA[i:], m.Trader)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.Trader)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MarginPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MarginPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MarginPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastLiquidationHeight != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.LastLiquidationHeight))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.TotalLiquidations != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.TotalLiquidations))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.LastTwapPrice) > 0 {
		i -= len(m.LastTwapPrice)
		copy(dAtA[i:], m.LastTwapPrice)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.LastTwapPrice)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.LastMarkPrice) > 0 {
		i -= len(m.LastMarkPrice)
		copy(dAtA[i:], m.LastMarkPrice)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.LastMarkPrice)))
		i--
		dAtA[i] = 0x72
	}
	if m.LiquidationsPaused {
		i--
		if m.LiquidationsPaused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if len(m.TotalBadDebt) > 0 {
		i -= len(m.TotalBadDebt)
		copy(dAtA[i:], m.TotalBadDebt)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.TotalBadDebt)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.TotalLiquidationFees) > 0 {
		i -= len(m.TotalLiquidationFees)
		copy(dAtA[i:], m.TotalLiquidationFees)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.TotalLiquidationFees)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.InsuranceFund) > 0 {
		i -= len(m.InsuranceFund)
		copy(dAtA[i:], m.InsuranceFund)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.InsuranceFund)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.CumulativeFundingRate) > 0 {
		i -= len(m.CumulativeFundingRate)
		copy(dAtA[i:], m.CumulativeFundingRate)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.CumulativeFundingRate)))
		i--
		dAtA[i] = 0x4a
	}
	if m.LastFundingTimestamp != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.LastFundingTimestamp))
		i--
		dAtA[i] = 0x40
	}
	if m.NextPositionId != 0 {
		i = encodeVarintMargin(dAtA, i, uint64(m.NextPositionId))
		i--
		dAtA[i] = 0x38
	}
	if len(m.MaintenanceMarginRatio) > 0 {
		i -= len(m.MaintenanceMarginRatio)
		copy(dAtA[i:], m.MaintenanceMarginRatio)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.MaintenanceMarginRatio)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.TotalShortExposure) > 0 {
		i -= len(m.TotalShortExposure)
		copy(dAtA[i:], m.TotalShortExposure)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.TotalShortExposure)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TotalLongExposure) > 0 {
		i -= len(m.TotalLongExposure)
		copy(dAtA[i:], m.TotalLongExposure)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.TotalLongExposure)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AvailableLiquidity) > 0 {
		i -= len(m.AvailableLiquidity)
		copy(dAtA[i:], m.AvailableLiquidity)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.AvailableLiquidity)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TotalCollateral) > 0 {
		i -= len(m.TotalCollateral)
		copy(dAtA[i:], m.TotalCollateral)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.TotalCollateral)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintMargin(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMargin(dAtA []byte, offset int, v uint64) int {
	offset -= sovMargin(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MarginPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMargin(uint64(m.Id))
	}
	l = len(m.Trader)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.CollateralDenom)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.CollateralAmount)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.PositionSize)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.EntryPrice)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	if m.Leverage != 0 {
		n += 1 + sovMargin(uint64(m.Leverage))
	}
	if m.Type != 0 {
		n += 1 + sovMargin(uint64(m.Type))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovMargin(uint64(m.CreatedAt))
	}
	l = len(m.LiquidationPrice)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.MaintenanceMargin)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.FundingFeeAccrued)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovMargin(uint64(m.Status))
	}
	l = len(m.RealizedPnl)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.LastMarkPrice)
	if l > 0 {
		n += 2 + l + sovMargin(uint64(l))
	}
	if m.PriceSource != 0 {
		n += 2 + sovMargin(uint64(m.PriceSource))
	}
	return n
}

func (m *MarginPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.TotalCollateral)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.AvailableLiquidity)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.TotalLongExposure)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.TotalShortExposure)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.MaintenanceMarginRatio)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	if m.NextPositionId != 0 {
		n += 1 + sovMargin(uint64(m.NextPositionId))
	}
	if m.LastFundingTimestamp != 0 {
		n += 1 + sovMargin(uint64(m.LastFundingTimestamp))
	}
	l = len(m.CumulativeFundingRate)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.InsuranceFund)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.TotalLiquidationFees)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.TotalBadDebt)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	if m.LiquidationsPaused {
		n += 2
	}
	l = len(m.LastMarkPrice)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	l = len(m.LastTwapPrice)
	if l > 0 {
		n += 1 + l + sovMargin(uint64(l))
	}
	if m.TotalLiquidations != 0 {
		n += 2 + sovMargin(uint64(m.TotalLiquidations))
	}
	if m.LastLiquidationHeight != 0 {
		n += 2 + sovMargin(uint64(m.LastLiquidationHeight))
	}
	return n
}

func sovMargin(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMargin(x uint64) (n int) {
	return sovMargin(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MarginPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMargin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarginPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarginPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trader", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Trader = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionSize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PositionSize = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EntryPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EntryPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Leverage", wireType)
			}
			m.Leverage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Leverage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= PositionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaintenanceMargin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaintenanceMargin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundingFeeAccrued", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FundingFeeAccrued = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PositionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealizedPnl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RealizedPnl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMarkPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastMarkPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceSource", wireType)
			}
			m.PriceSource = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceSource |= PriceSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMargin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMargin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MarginPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMargin
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MarginPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MarginPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCollateral", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalCollateral = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableLiquidity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvailableLiquidity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLongExposure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalLongExposure = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShortExposure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalShortExposure = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaintenanceMarginRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaintenanceMarginRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextPositionId", wireType)
			}
			m.NextPositionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextPositionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastFundingTimestamp", wireType)
			}
			m.LastFundingTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastFundingTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativeFundingRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CumulativeFundingRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InsuranceFund", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InsuranceFund = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLiquidationFees", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalLiquidationFees = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBadDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalBadDebt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationsPaused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LiquidationsPaused = bool(v != 0)
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastMarkPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastMarkPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastTwapPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMargin
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMargin
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastTwapPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLiquidations", wireType)
			}
			m.TotalLiquidations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalLiquidations |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastLiquidationHeight", wireType)
			}
			m.LastLiquidationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastLiquidationHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMargin(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMargin
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMargin(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMargin
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMargin
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMargin
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMargin
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMargin
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMargin        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMargin          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMargin = fmt.Errorf("proto: unexpected end of group")
)
