// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/bondingcurve/v1beta1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	BondingCurveWallet   string        `protobuf:"bytes,1,opt,name=bonding_curve_wallet,json=bondingCurveWallet,proto3" json:"bonding_curve_wallet,omitempty"`
	QuoteDenom           string        `protobuf:"bytes,2,opt,name=quote_denom,json=quoteDenom,proto3" json:"quote_denom,omitempty"`
	MaxSupply            string        `protobuf:"bytes,3,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	StartPrice           string        `protobuf:"bytes,4,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	EndPrice             string        `protobuf:"bytes,5,opt,name=end_price,json=endPrice,proto3" json:"end_price,omitempty"`
	TokenCreationFee     types.Coin    `protobuf:"bytes,6,opt,name=token_creation_fee,json=tokenCreationFee,proto3" json:"token_creation_fee"`
	FounderClaimPeriod   time.Duration `protobuf:"bytes,7,opt,name=founder_claim_period,json=founderClaimPeriod,proto3,stdduration" json:"founder_claim_period"`
	MaxLeverage          uint32        `protobuf:"varint,8,opt,name=max_leverage,json=maxLeverage,proto3" json:"max_leverage,omitempty"`
	LiquidationPenalty   string        `protobuf:"bytes,9,opt,name=liquidation_penalty,json=liquidationPenalty,proto3" json:"liquidation_penalty,omitempty"`
	ProtocolFeeRate      string        `protobuf:"bytes,10,opt,name=protocol_fee_rate,json=protocolFeeRate,proto3" json:"protocol_fee_rate,omitempty"`
	MinCollateralRatio   string        `protobuf:"bytes,11,opt,name=min_collateral_ratio,json=minCollateralRatio,proto3" json:"min_collateral_ratio,omitempty"`
	MarginTradingEnabled bool          `protobuf:"varint,12,opt,name=margin_trading_enabled,json=marginTradingEnabled,proto3" json:"margin_trading_enabled,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_886c678f7f1ef953, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBondingCurveWallet() string {
	if m != nil {
		return m.BondingCurveWallet
	}
	return ""
}

func (m *Params) GetQuoteDenom() string {
	if m != nil {
		return m.QuoteDenom
	}
	return ""
}

func (m *Params) GetMaxSupply() string {
	if m != nil {
		return m.MaxSupply
	}
	return ""
}

func (m *Params) GetStartPrice() string {
	if m != nil {
		return m.StartPrice
	}
	return ""
}

func (m *Params) GetEndPrice() string {
	if m != nil {
		return m.EndPrice
	}
	return ""
}

func (m *Params) GetTokenCreationFee() types.Coin {
	if m != nil {
		return m.TokenCreationFee
	}
	return types.Coin{}
}

func (m *Params) GetFounderClaimPeriod() time.Duration {
	if m != nil {
		return m.FounderClaimPeriod
	}
	return 0
}

func (m *Params) GetMaxLeverage() uint32 {
	if m != nil {
		return m.MaxLeverage
	}
	return 0
}

func (m *Params) GetLiquidationPenalty() string {
	if m != nil {
		return m.LiquidationPenalty
	}
	return ""
}

func (m *Params) GetProtocolFeeRate() string {
	if m != nil {
		return m.ProtocolFeeRate
	}
	return ""
}

func (m *Params) GetMinCollateralRatio() string {
	if m != nil {
		return m.MinCollateralRatio
	}
	return ""
}

func (m *Params) GetMarginTradingEnabled() bool {
	if m != nil {
		return m.MarginTradingEnabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "osmosis.bondingcurve.v1beta1.Params")
}

func init() {
	proto.RegisterFile("osmosis/bondingcurve/v1beta1/params.proto", fileDescriptor_886c678f7f1ef953)
}

var fileDescriptor_886c678f7f1ef953 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0x18, 0xa5, 0x75, 0x87, 0x00, 0x53, 0xa1, 0x30, 0x20, 0x2d, 0x9c, 0x0a, 0x12,
	0xc9, 0xc6, 0x38, 0x70, 0x6e, 0xc7, 0x4e, 0x20, 0x55, 0x01, 0x84, 0xc4, 0xc5, 0x72, 0x92, 0xb7,
	0xc1, 0xc2, 0xb1, 0x33, 0xc7, 0x29, 0xed, 0xb7, 0xe0, 0xc8, 0x27, 0x42, 0x3b, 0xee, 0xc8, 0x09,
	0x50, 0xfb, 0x45, 0x90, 0xff, 0x14, 0xc6, 0xcd, 0x7e, 0x7e, 0xef, 0xf3, 0xda, 0xef, 0x13, 0x07,
	0x3d, 0x91, 0x4d, 0x25, 0x1b, 0xd6, 0x24, 0x99, 0x14, 0x05, 0x13, 0x65, 0xde, 0xaa, 0x25, 0x24,
	0xcb, 0xa3, 0x0c, 0x34, 0x3d, 0x4a, 0x6a, 0xaa, 0x68, 0xd5, 0xc4, 0xb5, 0x92, 0x5a, 0xe2, 0x07,
	0xbe, 0x34, 0xbe, 0x5c, 0x1a, 0xfb, 0xd2, 0x83, 0x28, 0xb7, 0x38, 0xc9, 0x68, 0xf3, 0xcf, 0x9f,
	0x4b, 0x26, 0x9c, 0xfb, 0x20, 0x2a, 0xa5, 0x2c, 0x39, 0x24, 0x76, 0x97, 0xb5, 0x8b, 0xa4, 0x68,
	0x15, 0xd5, 0x4c, 0xee, 0xf8, 0xb0, 0x94, 0xa5, 0xb4, 0xcb, 0xc4, 0xac, 0x9c, 0xfa, 0xf8, 0xfb,
	0x1e, 0xea, 0xce, 0xed, 0x25, 0xf0, 0x21, 0x1a, 0xfa, 0x83, 0x89, 0x3d, 0x99, 0x7c, 0xa1, 0x9c,
	0x83, 0x0e, 0x83, 0x71, 0x30, 0xe9, 0xa7, 0xd8, 0xb3, 0x99, 0x41, 0x1f, 0x2c, 0xc1, 0x23, 0x34,
	0x38, 0x6b, 0xa5, 0x06, 0x52, 0x80, 0x90, 0x55, 0x78, 0xc5, 0x16, 0x22, 0x2b, 0x9d, 0x18, 0x05,
	0x3f, 0x44, 0xa8, 0xa2, 0x2b, 0xd2, 0xb4, 0x75, 0xcd, 0xd7, 0xe1, 0x55, 0xcb, 0xfb, 0x15, 0x5d,
	0xbd, 0xb5, 0x82, 0xf1, 0x37, 0x9a, 0x2a, 0x4d, 0x6a, 0xc5, 0x72, 0x08, 0xf7, 0x9c, 0xdf, 0x4a,
	0x73, 0xa3, 0xe0, 0xfb, 0xa8, 0x0f, 0xa2, 0xf0, 0xf8, 0x9a, 0xc5, 0x3d, 0x10, 0x85, 0x83, 0x6f,
	0x10, 0xd6, 0xf2, 0x33, 0x08, 0x92, 0x2b, 0xb0, 0x83, 0x92, 0x05, 0x40, 0xd8, 0x1d, 0x07, 0x93,
	0xc1, 0xf3, 0x7b, 0xb1, 0x4b, 0x2b, 0x36, 0x69, 0xed, 0x22, 0x8c, 0x67, 0x92, 0x89, 0xe9, 0xde,
	0xf9, 0xcf, 0x51, 0x27, 0xbd, 0x65, 0xad, 0x33, 0xef, 0x3c, 0x05, 0xc0, 0xef, 0xd1, 0x70, 0x21,
	0x5b, 0x51, 0x80, 0x22, 0x39, 0xa7, 0xac, 0x22, 0x35, 0x28, 0x26, 0x8b, 0xf0, 0xba, 0x6f, 0xe8,
	0xe2, 0x8d, 0x77, 0xf1, 0xc6, 0x27, 0x3e, 0xde, 0x69, 0xcf, 0x34, 0xfc, 0xf6, 0x6b, 0x14, 0xa4,
	0xd8, 0x37, 0x98, 0x19, 0xff, 0xdc, 0xda, 0xf1, 0x23, 0xb4, 0x6f, 0x22, 0xe0, 0xb0, 0x04, 0x45,
	0x4b, 0x08, 0x7b, 0xe3, 0x60, 0x72, 0x23, 0x1d, 0x54, 0x74, 0xf5, 0xda, 0x4b, 0x38, 0x41, 0x77,
	0x38, 0x3b, 0x6b, 0x59, 0xe1, 0xa6, 0xa8, 0x41, 0x50, 0xae, 0xd7, 0x61, 0xdf, 0xe5, 0x7e, 0x09,
	0xcd, 0x1d, 0xc1, 0x4f, 0xd1, 0x6d, 0x7b, 0x8d, 0x5c, 0x72, 0x33, 0x33, 0x51, 0x54, 0x43, 0x88,
	0x6c, 0xf9, 0xcd, 0x1d, 0x38, 0x05, 0x48, 0xa9, 0x06, 0xf3, 0x55, 0x2b, 0x26, 0x48, 0x2e, 0x39,
	0xa7, 0x1a, 0x14, 0xe5, 0xc4, 0x5e, 0x3b, 0x1c, 0xb8, 0xee, 0x15, 0x13, 0xb3, 0xbf, 0x28, 0x35,
	0x04, 0xbf, 0x40, 0x77, 0x2b, 0xaa, 0x4a, 0x26, 0x88, 0x56, 0xd4, 0x3e, 0x07, 0x10, 0x34, 0xe3,
	0x50, 0x84, 0xfb, 0xe3, 0x60, 0xd2, 0x4b, 0x87, 0x8e, 0xbe, 0x73, 0xf0, 0x95, 0x63, 0xd3, 0xf4,
	0x7c, 0x13, 0x05, 0x17, 0x9b, 0x28, 0xf8, 0xbd, 0x89, 0x82, 0xaf, 0xdb, 0xa8, 0x73, 0xb1, 0x8d,
	0x3a, 0x3f, 0xb6, 0x51, 0xe7, 0xe3, 0xcb, 0x92, 0xe9, 0x4f, 0x6d, 0x16, 0xe7, 0xb2, 0x4a, 0xfc,
	0x0b, 0x7f, 0xc6, 0x69, 0xd6, 0xec, 0x36, 0xc9, 0xf2, 0xf8, 0x30, 0x59, 0xfd, 0xff, 0x7f, 0xe8,
	0x75, 0x0d, 0x4d, 0xd6, 0xb5, 0xc3, 0x1c, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x50, 0x04,
	0xe4, 0x44, 0x03, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MarginTradingEnabled {
		i--
		if m.MarginTradingEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.MinCollateralRatio) > 0 {
		i -= len(m.MinCollateralRatio)
		copy(dAtA[i:], m.MinCollateralRatio)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinCollateralRatio)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ProtocolFeeRate) > 0 {
		i -= len(m.ProtocolFeeRate)
		copy(dAtA[i:], m.ProtocolFeeRate)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ProtocolFeeRate)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LiquidationPenalty) > 0 {
		i -= len(m.LiquidationPenalty)
		copy(dAtA[i:], m.LiquidationPenalty)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LiquidationPenalty)))
		i--
		dAtA[i] = 0x4a
	}
	if m.MaxLeverage != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxLeverage))
		i--
		dAtA[i] = 0x40
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.FounderClaimPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FounderClaimPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.TokenCreationFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.EndPrice) > 0 {
		i -= len(m.EndPrice)
		copy(dAtA[i:], m.EndPrice)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EndPrice)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StartPrice) > 0 {
		i -= len(m.StartPrice)
		copy(dAtA[i:], m.StartPrice)
		i = encodeVarintParams(dAtA, i, uint64(len(m.StartPrice)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.MaxSupply) > 0 {
		i -= len(m.MaxSupply)
		copy(dAtA[i:], m.MaxSupply)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MaxSupply)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.QuoteDenom) > 0 {
		i -= len(m.QuoteDenom)
		copy(dAtA[i:], m.QuoteDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.QuoteDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BondingCurveWallet) > 0 {
		i -= len(m.BondingCurveWallet)
		copy(dAtA[i:], m.BondingCurveWallet)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BondingCurveWallet)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BondingCurveWallet)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.QuoteDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MaxSupply)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.StartPrice)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EndPrice)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.TokenCreationFee.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.FounderClaimPeriod)
	n += 1 + l + sovParams(uint64(l))
	if m.MaxLeverage != 0 {
		n += 1 + sovParams(uint64(m.MaxLeverage))
	}
	l = len(m.LiquidationPenalty)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ProtocolFeeRate)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.MinCollateralRatio)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.MarginTradingEnabled {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingCurveWallet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondingCurveWallet = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxSupply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndPrice = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenCreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FounderClaimPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.FounderClaimPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxLeverage", wireType)
			}
			m.MaxLeverage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxLeverage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationPenalty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidationPenalty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProtocolFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProtocolFeeRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCollateralRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinCollateralRatio = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarginTradingEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MarginTradingEnabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
