// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: osmosis/bondingcurve/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGlobalPauseRequest struct {
}

func (m *QueryGlobalPauseRequest) Reset()         { *m = QueryGlobalPauseRequest{} }
func (m *QueryGlobalPauseRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGlobalPauseRequest) ProtoMessage()    {}
func (*QueryGlobalPauseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{2}
}
func (m *QueryGlobalPauseRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGlobalPauseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGlobalPauseRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGlobalPauseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGlobalPauseRequest.Merge(m, src)
}
func (m *QueryGlobalPauseRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGlobalPauseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGlobalPauseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGlobalPauseRequest proto.InternalMessageInfo

type QueryGlobalPauseResponse struct {
	Status *PauseInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *QueryGlobalPauseResponse) Reset()         { *m = QueryGlobalPauseResponse{} }
func (m *QueryGlobalPauseResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGlobalPauseResponse) ProtoMessage()    {}
func (*QueryGlobalPauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{3}
}
func (m *QueryGlobalPauseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGlobalPauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGlobalPauseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGlobalPauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGlobalPauseResponse.Merge(m, src)
}
func (m *QueryGlobalPauseResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGlobalPauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGlobalPauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGlobalPauseResponse proto.InternalMessageInfo

func (m *QueryGlobalPauseResponse) GetStatus() *PauseInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

type QueryTokenPauseRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryTokenPauseRequest) Reset()         { *m = QueryTokenPauseRequest{} }
func (m *QueryTokenPauseRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTokenPauseRequest) ProtoMessage()    {}
func (*QueryTokenPauseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{4}
}
func (m *QueryTokenPauseRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenPauseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenPauseRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenPauseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenPauseRequest.Merge(m, src)
}
func (m *QueryTokenPauseRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenPauseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenPauseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenPauseRequest proto.InternalMessageInfo

func (m *QueryTokenPauseRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryTokenPauseResponse struct {
	Status *PauseInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *QueryTokenPauseResponse) Reset()         { *m = QueryTokenPauseResponse{} }
func (m *QueryTokenPauseResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTokenPauseResponse) ProtoMessage()    {}
func (*QueryTokenPauseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{5}
}
func (m *QueryTokenPauseResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenPauseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenPauseResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenPauseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenPauseResponse.Merge(m, src)
}
func (m *QueryTokenPauseResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenPauseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenPauseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenPauseResponse proto.InternalMessageInfo

func (m *QueryTokenPauseResponse) GetStatus() *PauseInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

type QueryFreezeRequest struct {
	TargetType FreezeTargetType `protobuf:"varint,1,opt,name=target_type,json=targetType,proto3,enum=osmosis.bondingcurve.v1beta1.FreezeTargetType" json:"target_type,omitempty"`
	Target     string           `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (m *QueryFreezeRequest) Reset()         { *m = QueryFreezeRequest{} }
func (m *QueryFreezeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFreezeRequest) ProtoMessage()    {}
func (*QueryFreezeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{6}
}
func (m *QueryFreezeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFreezeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFreezeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFreezeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFreezeRequest.Merge(m, src)
}
func (m *QueryFreezeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFreezeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFreezeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFreezeRequest proto.InternalMessageInfo

func (m *QueryFreezeRequest) GetTargetType() FreezeTargetType {
	if m != nil {
		return m.TargetType
	}
	return FreezeTargetType_FREEZE_TARGET_TYPE_UNSPECIFIED
}

func (m *QueryFreezeRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type QueryFreezeResponse struct {
	Status *FreezeInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *QueryFreezeResponse) Reset()         { *m = QueryFreezeResponse{} }
func (m *QueryFreezeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFreezeResponse) ProtoMessage()    {}
func (*QueryFreezeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{7}
}
func (m *QueryFreezeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFreezeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFreezeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFreezeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFreezeResponse.Merge(m, src)
}
func (m *QueryFreezeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFreezeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFreezeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFreezeResponse proto.InternalMessageInfo

func (m *QueryFreezeResponse) GetStatus() *FreezeInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

type QueryPendingParamsRequest struct {
}

func (m *QueryPendingParamsRequest) Reset()         { *m = QueryPendingParamsRequest{} }
func (m *QueryPendingParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPendingParamsRequest) ProtoMessage()    {}
func (*QueryPendingParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{8}
}
func (m *QueryPendingParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingParamsRequest.Merge(m, src)
}
func (m *QueryPendingParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingParamsRequest proto.InternalMessageInfo

type QueryPendingParamsResponse struct {
	PendingParams *PendingParams `protobuf:"bytes,1,opt,name=pending_params,json=pendingParams,proto3" json:"pending_params,omitempty"`
}

func (m *QueryPendingParamsResponse) Reset()         { *m = QueryPendingParamsResponse{} }
func (m *QueryPendingParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPendingParamsResponse) ProtoMessage()    {}
func (*QueryPendingParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{9}
}
func (m *QueryPendingParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPendingParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPendingParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPendingParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPendingParamsResponse.Merge(m, src)
}
func (m *QueryPendingParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPendingParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPendingParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPendingParamsResponse proto.InternalMessageInfo

func (m *QueryPendingParamsResponse) GetPendingParams() *PendingParams {
	if m != nil {
		return m.PendingParams
	}
	return nil
}

type QueryEmergencyActionsRequest struct {
	Limit uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *QueryEmergencyActionsRequest) Reset()         { *m = QueryEmergencyActionsRequest{} }
func (m *QueryEmergencyActionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyActionsRequest) ProtoMessage()    {}
func (*QueryEmergencyActionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{10}
}
func (m *QueryEmergencyActionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyActionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyActionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyActionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyActionsRequest.Merge(m, src)
}
func (m *QueryEmergencyActionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyActionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyActionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyActionsRequest proto.InternalMessageInfo

func (m *QueryEmergencyActionsRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type QueryEmergencyActionsResponse struct {
	Actions []*EmergencyAction `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (m *QueryEmergencyActionsResponse) Reset()         { *m = QueryEmergencyActionsResponse{} }
func (m *QueryEmergencyActionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyActionsResponse) ProtoMessage()    {}
func (*QueryEmergencyActionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{11}
}
func (m *QueryEmergencyActionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyActionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyActionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyActionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyActionsResponse.Merge(m, src)
}
func (m *QueryEmergencyActionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyActionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyActionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyActionsResponse proto.InternalMessageInfo

func (m *QueryEmergencyActionsResponse) GetActions() []*EmergencyAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

type QueryEmergencyConfigRequest struct {
}

func (m *QueryEmergencyConfigRequest) Reset()         { *m = QueryEmergencyConfigRequest{} }
func (m *QueryEmergencyConfigRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyConfigRequest) ProtoMessage()    {}
func (*QueryEmergencyConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{12}
}
func (m *QueryEmergencyConfigRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyConfigRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyConfigRequest.Merge(m, src)
}
func (m *QueryEmergencyConfigRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyConfigRequest proto.InternalMessageInfo

type QueryEmergencyConfigResponse struct {
	Config *EmergencyConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (m *QueryEmergencyConfigResponse) Reset()         { *m = QueryEmergencyConfigResponse{} }
func (m *QueryEmergencyConfigResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyConfigResponse) ProtoMessage()    {}
func (*QueryEmergencyConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f560f465c3e155da, []int{13}
}
func (m *QueryEmergencyConfigResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyConfigResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyConfigResponse.Merge(m, src)
}
func (m *QueryEmergencyConfigResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyConfigResponse proto.InternalMessageInfo

func (m *QueryEmergencyConfigResponse) GetConfig() *EmergencyConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "osmosis.bondingcurve.v1beta1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "osmosis.bondingcurve.v1beta1.QueryParamsResponse")
	proto.RegisterType((*QueryGlobalPauseRequest)(nil), "osmosis.bondingcurve.v1beta1.QueryGlobalPauseRequest")
	proto.RegisterType((*QueryGlobalPauseResponse)(nil), "osmosis.bondingcurve.v1beta1.QueryGlobalPauseResponse")
	proto.RegisterType((*QueryTokenPauseRequest)(nil), "osmosis.bondingcurve.v1beta1.QueryTokenPauseRequest")
	proto.RegisterType((*QueryTokenPauseResponse)(nil), "osmosis.bondingcurve.v1beta1.QueryTokenPauseResponse")
	proto.RegisterType((*QueryFreezeRequest)(nil), "osmosis.bondingcurve.v1beta1.QueryFreezeRequest")
	proto.RegisterType((*QueryFreezeResponse)(nil), "osmosis.bondingcurve.v1beta1.QueryFreezeResponse")
	proto.RegisterType((*QueryPendingParamsRequest)(nil), "osmosis.bondingcurve.v1beta1.QueryPendingParamsRequest")
	proto.RegisterType((*QueryPendingParamsResponse)(nil), "osmosis.bondingcurve.v1beta1.QueryPendingParamsResponse")
	proto.RegisterType((*QueryEmergencyActionsRequest)(nil), "osmosis.bondingcurve.v1beta1.QueryEmergencyActionsRequest")
	proto.RegisterType((*QueryEmergencyActionsResponse)(nil), "osmosis.bondingcurve.v1beta1.QueryEmergencyActionsResponse")
	proto.RegisterType((*QueryEmergencyConfigRequest)(nil), "osmosis.bondingcurve.v1beta1.QueryEmergencyConfigRequest")
	proto.RegisterType((*QueryEmergencyConfigResponse)(nil), "osmosis.bondingcurve.v1beta1.QueryEmergencyConfigResponse")
}

func init() {
	proto.RegisterFile("osmosis/bondingcurve/v1beta1/query.proto", fileDescriptor_f560f465c3e155da)
}

var fileDescriptor_f560f465c3e155da = []byte{
	// 657 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4f, 0x4f, 0xd4, 0x40,
	0x14, 0xdf, 0x2a, 0xd4, 0xf8, 0x36, 0xa0, 0x19, 0x09, 0x2e, 0x05, 0x56, 0xd2, 0x68, 0x5c, 0x63,
	0x68, 0x61, 0x01, 0x45, 0x3c, 0xa8, 0x18, 0x24, 0x9e, 0xc4, 0x86, 0xc4, 0x88, 0x07, 0xd2, 0x5d,
	0x86, 0xd2, 0xb8, 0xed, 0x94, 0xce, 0x94, 0xb0, 0x46, 0x2f, 0x9e, 0x4c, 0xbc, 0xf8, 0xb1, 0x38,
	0x72, 0xf4, 0x64, 0x0c, 0x7c, 0x0d, 0x0f, 0x86, 0x99, 0x57, 0xdc, 0xee, 0x42, 0xe9, 0x12, 0x6f,
	0x7d, 0x9d, 0xdf, 0xbf, 0x79, 0xed, 0x9b, 0x81, 0x1a, 0xe3, 0x01, 0xe3, 0x3e, 0xb7, 0x1b, 0x2c,
	0xdc, 0xf2, 0x43, 0xaf, 0x99, 0xc4, 0x7b, 0xd4, 0xde, 0x9b, 0x6d, 0x50, 0xe1, 0xce, 0xda, 0xbb,
	0x09, 0x8d, 0xdb, 0x56, 0x14, 0x33, 0xc1, 0xc8, 0x04, 0x22, 0xad, 0x4e, 0xa4, 0x85, 0x48, 0x63,
	0xc4, 0x63, 0x1e, 0x93, 0x40, 0xfb, 0xe4, 0x49, 0x71, 0x8c, 0x7c, 0x75, 0x77, 0x2b, 0xf0, 0x43,
	0x44, 0x3e, 0xc8, 0x45, 0x46, 0x6e, 0xec, 0x06, 0x1c, 0xa1, 0xf7, 0x72, 0xa1, 0x62, 0x5f, 0xc1,
	0xcc, 0x11, 0x20, 0x6f, 0x4f, 0xe2, 0xaf, 0x49, 0xae, 0x43, 0x77, 0x13, 0xca, 0x85, 0xf9, 0x1e,
	0x6e, 0x65, 0xde, 0xf2, 0x88, 0x85, 0x9c, 0x92, 0x65, 0xd0, 0x95, 0x47, 0x45, 0x9b, 0xd2, 0x6a,
	0xe5, 0xfa, 0x5d, 0x2b, 0x6f, 0xb7, 0x96, 0x62, 0x2f, 0x0f, 0x1c, 0xfc, 0xba, 0x53, 0x72, 0x90,
	0x69, 0x8e, 0xc1, 0x6d, 0x29, 0xbd, 0xda, 0x62, 0x0d, 0xb7, 0xb5, 0xe6, 0x26, 0x9c, 0xa6, 0xae,
	0x1f, 0xa0, 0xd2, 0xbb, 0x84, 0xd6, 0xcf, 0x40, 0xe7, 0xc2, 0x15, 0x49, 0x6a, 0x7d, 0xff, 0x22,
	0xeb, 0x84, 0xd3, 0xd7, 0xe1, 0x36, 0x73, 0x90, 0x66, 0x5a, 0x30, 0x2a, 0xc5, 0xd7, 0xd9, 0x47,
	0x1a, 0x76, 0xda, 0x92, 0x11, 0x18, 0xdc, 0xa2, 0x21, 0x0b, 0xa4, 0xf2, 0x75, 0x47, 0x15, 0xe6,
	0x06, 0xe6, 0xec, 0xc4, 0xff, 0xaf, 0x2c, 0x5f, 0xb0, 0xe9, 0xaf, 0x62, 0x4a, 0x3f, 0x9d, 0xe6,
	0x78, 0x03, 0x65, 0xe1, 0xc6, 0x1e, 0x15, 0x9b, 0xa2, 0x1d, 0x51, 0xa9, 0x3d, 0x5c, 0xb7, 0xf2,
	0xb5, 0x95, 0xc2, 0xba, 0xa4, 0xad, 0xb7, 0x23, 0xea, 0x80, 0x38, 0x7d, 0x26, 0xa3, 0xa0, 0xab,
	0xaa, 0x72, 0x45, 0xee, 0x0c, 0x2b, 0xf3, 0x1d, 0x7e, 0xdd, 0xd4, 0x1e, 0xb7, 0xf5, 0xbc, 0x6b,
	0x5b, 0xb5, 0x22, 0xd6, 0x99, 0x7d, 0x8d, 0xc3, 0x98, 0xfa, 0x6d, 0xa8, 0xc4, 0x67, 0xff, 0xa9,
	0x08, 0x8c, 0xb3, 0x16, 0xd1, 0xdc, 0x81, 0xe1, 0x48, 0x2d, 0x6c, 0x66, 0x7e, 0xb1, 0x87, 0x17,
	0xf4, 0x36, 0x23, 0x36, 0x14, 0x75, 0x96, 0xe6, 0x3c, 0x4c, 0x48, 0xc7, 0x95, 0x80, 0xc6, 0x1e,
	0x0d, 0x9b, 0xed, 0x17, 0x4d, 0xe1, 0xb3, 0x90, 0x77, 0x7c, 0xf8, 0x96, 0x1f, 0xf8, 0x42, 0x5a,
	0x0d, 0x38, 0xaa, 0x30, 0x77, 0x60, 0xf2, 0x1c, 0x16, 0x46, 0x5d, 0x85, 0x6b, 0xae, 0x7a, 0x55,
	0xd1, 0xa6, 0xae, 0xd6, 0xca, 0xf5, 0xe9, 0xfc, 0x8c, 0x5d, 0x42, 0x4e, 0xca, 0x36, 0x27, 0x61,
	0x3c, 0xeb, 0xf4, 0x92, 0x85, 0xdb, 0xbe, 0x97, 0x36, 0x8c, 0x76, 0xc7, 0x4f, 0x97, 0x31, 0xc7,
	0x0a, 0xe8, 0x4d, 0xf9, 0x06, 0x5b, 0x55, 0x34, 0x06, 0xca, 0x20, 0xb9, 0xfe, 0x47, 0x87, 0x41,
	0xe9, 0x43, 0x02, 0xd0, 0x55, 0xe7, 0xc8, 0x4c, 0xbe, 0x54, 0xef, 0x89, 0x61, 0xcc, 0xf6, 0xc1,
	0xc0, 0xfc, 0x9f, 0xa1, 0xdc, 0x31, 0xe9, 0x64, 0xa1, 0x80, 0x42, 0xef, 0xa1, 0x61, 0x3c, 0xea,
	0x97, 0x86, 0xee, 0x6d, 0x80, 0x7f, 0xa3, 0x4d, 0xe6, 0x0b, 0xa8, 0xf4, 0x9c, 0x1c, 0xc6, 0x42,
	0x9f, 0x2c, 0xb4, 0x0e, 0x40, 0x57, 0xc3, 0x53, 0xa8, 0xcf, 0x99, 0x43, 0xa2, 0x50, 0x9f, 0xbb,
	0xe6, 0xfa, 0xab, 0x06, 0x43, 0x99, 0x39, 0x21, 0x8f, 0x8b, 0x7c, 0xac, 0x33, 0x66, 0xd8, 0x58,
	0xec, 0x9f, 0x88, 0x21, 0xbe, 0x6b, 0x70, 0xb3, 0x7b, 0xa2, 0xc8, 0x52, 0x01, 0xb9, 0x73, 0x86,
	0xd7, 0x78, 0x7a, 0x29, 0x2e, 0xa6, 0xf9, 0xa6, 0xc1, 0x8d, 0xae, 0x79, 0x20, 0x4f, 0xfa, 0x11,
	0xcc, 0x4c, 0xaa, 0xb1, 0x74, 0x19, 0xaa, 0x8a, 0xb2, 0xec, 0x1c, 0x1c, 0x55, 0xb5, 0xc3, 0xa3,
	0xaa, 0xf6, 0xfb, 0xa8, 0xaa, 0xfd, 0x38, 0xae, 0x96, 0x0e, 0x8f, 0xab, 0xa5, 0x9f, 0xc7, 0xd5,
	0xd2, 0xc6, 0xa2, 0xe7, 0x8b, 0x9d, 0xa4, 0x61, 0x35, 0x59, 0x60, 0xa3, 0xfe, 0x74, 0xcb, 0x6d,
	0xf0, 0xb4, 0xb0, 0xf7, 0xe6, 0x66, 0xec, 0xfd, 0xec, 0xfd, 0x7e, 0x72, 0x73, 0xf0, 0x86, 0x2e,
	0xef, 0xf6, 0xb9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0xfe, 0x97, 0x06, 0xb7, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	GlobalPause(ctx context.Context, in *QueryGlobalPauseRequest, opts ...grpc.CallOption) (*QueryGlobalPauseResponse, error)
	TokenPause(ctx context.Context, in *QueryTokenPauseRequest, opts ...grpc.CallOption) (*QueryTokenPauseResponse, error)
	Freeze(ctx context.Context, in *QueryFreezeRequest, opts ...grpc.CallOption) (*QueryFreezeResponse, error)
	PendingParams(ctx context.Context, in *QueryPendingParamsRequest, opts ...grpc.CallOption) (*QueryPendingParamsResponse, error)
	EmergencyActions(ctx context.Context, in *QueryEmergencyActionsRequest, opts ...grpc.CallOption) (*QueryEmergencyActionsResponse, error)
	EmergencyConfig(ctx context.Context, in *QueryEmergencyConfigRequest, opts ...grpc.CallOption) (*QueryEmergencyConfigResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/osmosis.bondingcurve.v1beta1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GlobalPause(ctx context.Context, in *QueryGlobalPauseRequest, opts ...grpc.CallOption) (*QueryGlobalPauseResponse, error) {
	out := new(QueryGlobalPauseResponse)
	err := c.cc.Invoke(ctx, "/osmosis.bondingcurve.v1beta1.Query/GlobalPause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TokenPause(ctx context.Context, in *QueryTokenPauseRequest, opts ...grpc.CallOption) (*QueryTokenPauseResponse, error) {
	out := new(QueryTokenPauseResponse)
	err := c.cc.Invoke(ctx, "/osmosis.bondingcurve.v1beta1.Query/TokenPause", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Freeze(ctx context.Context, in *QueryFreezeRequest, opts ...grpc.CallOption) (*QueryFreezeResponse, error) {
	out := new(QueryFreezeResponse)
	err := c.cc.Invoke(ctx, "/osmosis.bondingcurve.v1beta1.Query/Freeze", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PendingParams(ctx context.Context, in *QueryPendingParamsRequest, opts ...grpc.CallOption) (*QueryPendingParamsResponse, error) {
	out := new(QueryPendingParamsResponse)
	err := c.cc.Invoke(ctx, "/osmosis.bondingcurve.v1beta1.Query/PendingParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EmergencyActions(ctx context.Context, in *QueryEmergencyActionsRequest, opts ...grpc.CallOption) (*QueryEmergencyActionsResponse, error) {
	out := new(QueryEmergencyActionsResponse)
	err := c.cc.Invoke(ctx, "/osmosis.bondingcurve.v1beta1.Query/EmergencyActions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EmergencyConfig(ctx context.Context, in *QueryEmergencyConfigRequest, opts ...grpc.CallOption) (*QueryEmergencyConfigResponse, error) {
	out := new(QueryEmergencyConfigResponse)
	err := c.cc.Invoke(ctx, "/osmosis.bondingcurve.v1beta1.Query/EmergencyConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	GlobalPause(context.Context, *QueryGlobalPauseRequest) (*QueryGlobalPauseResponse, error)
	TokenPause(context.Context, *QueryTokenPauseRequest) (*QueryTokenPauseResponse, error)
	Freeze(context.Context, *QueryFreezeRequest) (*QueryFreezeResponse, error)
	PendingParams(context.Context, *QueryPendingParamsRequest) (*QueryPendingParamsResponse, error)
	EmergencyActions(context.Context, *QueryEmergencyActionsRequest) (*QueryEmergencyActionsResponse, error)
	EmergencyConfig(context.Context, *QueryEmergencyConfigRequest) (*QueryEmergencyConfigResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GlobalPause(ctx context.Context, req *QueryGlobalPauseRequest) (*QueryGlobalPauseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GlobalPause not implemented")
}
func (*UnimplementedQueryServer) TokenPause(ctx context.Context, req *QueryTokenPauseRequest) (*QueryTokenPauseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenPause not implemented")
}
func (*UnimplementedQueryServer) Freeze(ctx context.Context, req *QueryFreezeRequest) (*QueryFreezeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Freeze not implemented")
}
func (*UnimplementedQueryServer) PendingParams(ctx context.Context, req *QueryPendingParamsRequest) (*QueryPendingParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PendingParams not implemented")
}
func (*UnimplementedQueryServer) EmergencyActions(ctx context.Context, req *QueryEmergencyActionsRequest) (*QueryEmergencyActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyActions not implemented")
}
func (*UnimplementedQueryServer) EmergencyConfig(ctx context.Context, req *QueryEmergencyConfigRequest) (*QueryEmergencyConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyConfig not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.bondingcurve.v1beta1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GlobalPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGlobalPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GlobalPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.bondingcurve.v1beta1.Query/GlobalPause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GlobalPause(ctx, req.(*QueryGlobalPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TokenPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTokenPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TokenPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.bondingcurve.v1beta1.Query/TokenPause",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TokenPause(ctx, req.(*QueryTokenPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Freeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Freeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.bondingcurve.v1beta1.Query/Freeze",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Freeze(ctx, req.(*QueryFreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PendingParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPendingParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PendingParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.bondingcurve.v1beta1.Query/PendingParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PendingParams(ctx, req.(*QueryPendingParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EmergencyActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmergencyActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EmergencyActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.bondingcurve.v1beta1.Query/EmergencyActions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EmergencyActions(ctx, req.(*QueryEmergencyActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EmergencyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmergencyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EmergencyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/osmosis.bondingcurve.v1beta1.Query/EmergencyConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EmergencyConfig(ctx, req.(*QueryEmergencyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "osmosis.bondingcurve.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GlobalPause",
			Handler:    _Query_GlobalPause_Handler,
		},
		{
			MethodName: "TokenPause",
			Handler:    _Query_TokenPause_Handler,
		},
		{
			MethodName: "Freeze",
			Handler:    _Query_Freeze_Handler,
		},
		{
			MethodName: "PendingParams",
			Handler:    _Query_PendingParams_Handler,
		},
		{
			MethodName: "EmergencyActions",
			Handler:    _Query_EmergencyActions_Handler,
		},
		{
			MethodName: "EmergencyConfig",
			Handler:    _Query_EmergencyConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osmosis/bondingcurve/v1beta1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGlobalPauseRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGlobalPauseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGlobalPauseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGlobalPauseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGlobalPauseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGlobalPauseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenPauseRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenPauseRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenPauseRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenPauseResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenPauseResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenPauseResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFreezeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFreezeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFreezeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Target) > 0 {
		i -= len(m.Target)
		copy(dAtA[i:], m.Target)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Target)))
		i--
		dAtA[i] = 0x12
	}
	if m.TargetType != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TargetType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryFreezeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFreezeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFreezeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != nil {
		{
			size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPendingParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryPendingParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPendingParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPendingParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PendingParams != nil {
		{
			size, err := m.PendingParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyActionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyActionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyActionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyActionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyActionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyActionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Actions) > 0 {
		for iNdEx := len(m.Actions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Actions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyConfigRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyConfigRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyConfigRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyConfigResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyConfigResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyConfigResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Config != nil {
		{
			size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGlobalPauseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGlobalPauseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokenPauseRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokenPauseResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFreezeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TargetType != 0 {
		n += 1 + sovQuery(uint64(m.TargetType))
	}
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFreezeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != nil {
		l = m.Status.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPendingParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryPendingParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PendingParams != nil {
		l = m.PendingParams.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEmergencyActionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limit != 0 {
		n += 1 + sovQuery(uint64(m.Limit))
	}
	return n
}

func (m *QueryEmergencyActionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Actions) > 0 {
		for _, e := range m.Actions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryEmergencyConfigRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEmergencyConfigResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Config != nil {
		l = m.Config.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGlobalPauseRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGlobalPauseRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGlobalPauseRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGlobalPauseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGlobalPauseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGlobalPauseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &PauseInfo{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenPauseRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenPauseRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenPauseRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenPauseResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenPauseResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenPauseResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &PauseInfo{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFreezeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFreezeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFreezeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetType", wireType)
			}
			m.TargetType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetType |= FreezeTargetType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFreezeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFreezeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFreezeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Status == nil {
				m.Status = &FreezeInfo{}
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPendingParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPendingParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPendingParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PendingParams == nil {
				m.PendingParams = &PendingParams{}
			}
			if err := m.PendingParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyActionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyActionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyActionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyActionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyActionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyActionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Actions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Actions = append(m.Actions, &EmergencyAction{})
			if err := m.Actions[len(m.Actions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyConfigRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyConfigRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyConfigRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyConfigResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyConfigResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyConfigResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = &EmergencyConfig{}
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
