// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: mychain/assets/v1/tx.proto

package types

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"
)

// REST handlers are not exposed for the assets Msg service yet. Stub out the
// standard gateway registration helpers to keep the linker satisfied.

func RegisterMsgHandlerServer(context.Context, *runtime.ServeMux, MsgServer) error {
	return nil
}

func RegisterMsgHandler(context.Context, *runtime.ServeMux, *grpc.ClientConn) error {
	return nil
}

func RegisterMsgHandlerClient(context.Context, *runtime.ServeMux, MsgClient) error {
	return nil
}

func RegisterMsgHandlerFromEndpoint(context.Context, *runtime.ServeMux, string, []grpc.DialOption) error {
	return nil
}
